import type { ImageSourcePropType } from "react-native";

export type AvatarGender = "m" | "f";
export type AvatarStyle = "90s" | "1920s" | "1950s" | "1970s" | "1980s" | "Y2K";

export type AvatarDefinition = { id: string; face: string; emotion: string; gender: AvatarGender; style: AvatarStyle; source: ImageSourcePropType; thumbnail: ImageSourcePropType; neutral?: boolean };

export const AVATAR_DEFINITIONS: AvatarDefinition[] = [
  { id: "item-20s-boa", face: "Feather Boa", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-boa.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-boa.webp") },
  { id: "item-20s-camera", face: "Silent Film Camera", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-camera.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-camera.webp") },
  { id: "item-20s-gramophone", face: "Gramophone", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-gramophone.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-gramophone.webp") },
  { id: "item-20s-headband", face: "Flapper Headband", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-headband.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-headband.webp") },
  { id: "item-20s-modelt", face: "Model T", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-modelt.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-modelt.webp") },
  { id: "item-20s-radio", face: "Art Deco Radio", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-radio.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-radio.webp") },
  { id: "item-20s-saxophone", face: "Jazz Saxophone", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-saxophone.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-saxophone.webp") },
  { id: "item-20s-watch", face: "Pocket Watch", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-watch.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-watch.webp") },
  { id: "item-50s-jacket", face: "Leather Jacket", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-jacket.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-jacket.webp") },
  { id: "item-50s-jukebox", face: "Jukebox", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-jukebox.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-jukebox.webp") },
  { id: "item-50s-milkshake", face: "Milkshake", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-milkshake.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-milkshake.webp") },
  { id: "item-50s-poodle", face: "Poodle Skirt", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-poodle.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-poodle.webp") },
  { id: "item-50s-rotary", face: "Rotary Phone", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-rotary.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-rotary.webp") },
  { id: "item-50s-speaker", face: "Drive-In Speaker", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-speaker.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-speaker.webp") },
  { id: "item-50s-tailfin", face: "Car Tailfin", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-tailfin.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-tailfin.webp") },
  { id: "item-50s-vinyl45", face: "Vinyl 45", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-vinyl45.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-vinyl45.webp") },
  { id: "item-70s-8track", face: "8-Track Tape", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-8track.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-8track.webp") },
  { id: "item-70s-bellbottoms", face: "Bell-Bottom Jeans", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-bellbottoms.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-bellbottoms.webp") },
  { id: "item-70s-cassette", face: "Cassette Tape", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-cassette.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-cassette.webp") },
  { id: "item-70s-cbradio", face: "CB Radio", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-cbradio.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-cbradio.webp") },
  { id: "item-70s-fondue", face: "Fondue Pot", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-fondue.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-fondue.webp") },
  { id: "item-70s-lavalamp", face: "Lava Lamp", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-lavalamp.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-lavalamp.webp") },
  { id: "item-70s-petrock", face: "Pet Rock", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-petrock.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-petrock.webp") },
  { id: "item-70s-skate", face: "Roller Skate", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-skate.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-skate.webp") },
  { id: "item-80s-boombox", face: "Boombox", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-boombox.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-boombox.webp") },
  { id: "item-80s-bracelet", face: "Slap Bracelet", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-bracelet.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-bracelet.webp") },
  { id: "item-80s-mixtape", face: "Mixtape", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-mixtape.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-mixtape.webp") },
  { id: "item-80s-phone", face: "Corded Phone", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-phone.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-phone.webp") },
  { id: "item-80s-rubiks", face: "Rubik\'s Cube", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-rubiks.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-rubiks.webp") },
  { id: "item-80s-shades", face: "Neon Sunglasses", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-shades.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-shades.webp") },
  { id: "item-80s-token", face: "Arcade Token", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-token.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-token.webp") },
  { id: "item-80s-vhs", face: "VHS Tape", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-vhs.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-vhs.webp") },
  { id: "item-90s-cd", face: "Compact Disc", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-cd.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-cd.webp") },
  { id: "item-90s-gameboy", face: "Game Boy", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-gameboy.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-gameboy.webp") },
  { id: "item-90s-inflate", face: "Inflatable Chair", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-inflate.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-inflate.webp") },
  { id: "item-90s-pager", face: "Pager", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-pager.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-pager.webp") },
  { id: "item-90s-rollerblades", face: "Rollerblades", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-rollerblades.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-rollerblades.webp") },
  { id: "item-90s-slapwatch", face: "Slap Watch", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-slapwatch.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-slapwatch.webp") },
  { id: "item-90s-tamagotchi", face: "Tamagotchi", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-tamagotchi.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-tamagotchi.webp") },
  { id: "item-90s-troll", face: "Troll Doll", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-troll.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-troll.webp") },
  { id: "item-y2k-backpack", face: "Inflatable Backpack", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-backpack.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-backpack.webp") },
  { id: "item-y2k-cdwallet", face: "CD Wallet", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-cdwallet.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-cdwallet.webp") },
  { id: "item-y2k-clips", face: "Butterfly Clips", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-clips.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-clips.webp") },
  { id: "item-y2k-gelpen", face: "Gel Pens", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-gelpen.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-gelpen.webp") },
  { id: "item-y2k-minidisc", face: "MiniDisc", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-minidisc.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-minidisc.webp") },
  { id: "item-y2k-mp3", face: "MP3 Player", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-mp3.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-mp3.webp") },
  { id: "item-y2k-sneakers", face: "Platform Sneakers", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-sneakers.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-sneakers.webp") },
  { id: "item-y2k-webcam", face: "Webcam", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-webcam.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-webcam.webp") },
  { id: "item-20s-typewriter", face: "Typewriter", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-typewriter.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-typewriter.webp") },
  { id: "item-20s-megaphone", face: "Megaphone", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-megaphone.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-megaphone.webp") },
  { id: "item-20s-danceshoes", face: "Dance Shoes", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-danceshoes.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-danceshoes.webp") },
  { id: "item-20s-pearls", face: "Pearl Necklace", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-pearls.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-pearls.webp") },
  { id: "item-20s-lamp", face: "Art Deco Lamp", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-lamp.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-lamp.webp") },
  { id: "item-20s-record", face: "Phonograph Record", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-record.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-record.webp") },
  { id: "item-20s-banjo", face: "Banjo", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-banjo.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-banjo.webp") },
  { id: "item-20s-projector", face: "Movie Projector", emotion: "Keepsake", gender: "m", style: "1920s", neutral: true, source: require("@/assets/avatars/avatar-item-20s-projector.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-20s-projector.webp") },
  { id: "item-50s-saddleshoes", face: "Saddle Shoes", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-saddleshoes.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-saddleshoes.webp") },
  { id: "item-50s-hulahoop", face: "Hula Hoop", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-hulahoop.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-hulahoop.webp") },
  { id: "item-50s-transistor", face: "Transistor Radio", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-transistor.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-transistor.webp") },
  { id: "item-50s-bobbysocks", face: "Bobby Socks", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-bobbysocks.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-bobbysocks.webp") },
  { id: "item-50s-letterman", face: "Letterman Jacket", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-letterman.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-letterman.webp") },
  { id: "item-50s-ticket", face: "Drive-In Ticket", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-ticket.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-ticket.webp") },
  { id: "item-50s-adapter", face: "45 Adapter", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-adapter.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-adapter.webp") },
  { id: "item-50s-menu", face: "Diner Menu", emotion: "Keepsake", gender: "m", style: "1950s", neutral: true, source: require("@/assets/avatars/avatar-item-50s-menu.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-50s-menu.webp") },
  { id: "item-70s-platforms", face: "Platform Shoes", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-platforms.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-platforms.webp") },
  { id: "item-70s-beanbag", face: "Beanbag Chair", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-beanbag.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-beanbag.webp") },
  { id: "item-70s-moodring", face: "Mood Ring", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-moodring.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-moodring.webp") },
  { id: "item-70s-tiedye", face: "Tie-Dye Shirt", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-tiedye.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-tiedye.webp") },
  { id: "item-70s-waterbed", face: "Waterbed", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-waterbed.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-waterbed.webp") },
  { id: "item-70s-calculator", face: "Pocket Calculator", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-calculator.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-calculator.webp") },
  { id: "item-70s-macrame", face: "Macrame Hanger", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-macrame.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-macrame.webp") },
  { id: "item-70s-forks", face: "Fondue Forks", emotion: "Keepsake", gender: "m", style: "1970s", neutral: true, source: require("@/assets/avatars/avatar-item-70s-forks.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-70s-forks.webp") },
  { id: "item-80s-legwarmers", face: "Leg Warmers", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-legwarmers.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-legwarmers.webp") },
  { id: "item-80s-rewinder", face: "VHS Rewinder", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-rewinder.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-rewinder.webp") },
  { id: "item-80s-clock", face: "Neon Clock", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-clock.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-clock.webp") },
  { id: "item-80s-case", face: "Cassette Case", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-case.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-case.webp") },
  { id: "item-80s-joystick", face: "Arcade Joystick", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-joystick.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-joystick.webp") },
  { id: "item-80s-shoulderpads", face: "Shoulder Pads", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-shoulderpads.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-shoulderpads.webp") },
  { id: "item-80s-swatch", face: "Swatch Watch", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-swatch.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-swatch.webp") },
  { id: "item-80s-fannypack", face: "Fanny Pack", emotion: "Keepsake", gender: "m", style: "1980s", neutral: true, source: require("@/assets/avatars/avatar-item-80s-fannypack.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-80s-fannypack.webp") },
  { id: "item-90s-supersoaker", face: "Super Soaker", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-supersoaker.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-supersoaker.webp") },
  { id: "item-90s-pogs", face: "Pogs", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-pogs.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-pogs.webp") },
  { id: "item-90s-skipit", face: "Skip-It", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-skipit.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-skipit.webp") },
  { id: "item-90s-bopit", face: "Bop It", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-bopit.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-bopit.webp") },
  { id: "item-90s-talkboy", face: "Talkboy", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-talkboy.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-talkboy.webp") },
  { id: "item-90s-gak", face: "Gak", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-gak.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-gak.webp") },
  { id: "item-90s-n64", face: "N64 Controller", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-n64.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-n64.webp") },
  { id: "item-90s-furby", face: "Furby", emotion: "Keepsake", gender: "m", style: "90s", neutral: true, source: require("@/assets/avatars/avatar-item-90s-furby.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-90s-furby.webp") },
  { id: "item-y2k-imac", face: "iMac G3", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-imac.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-imac.webp") },
  { id: "item-y2k-nokia", face: "Nokia 3310", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-nokia.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-nokia.webp") },
  { id: "item-y2k-scooter", face: "Razor Scooter", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-scooter.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-scooter.webp") },
  { id: "item-y2k-jellies", face: "Jelly Sandals", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-jellies.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-jellies.webp") },
  { id: "item-y2k-lipsmackers", face: "Lip Smackers", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-lipsmackers.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-lipsmackers.webp") },
  { id: "item-y2k-portabletv", face: "Portable TV", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-portabletv.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-portabletv.webp") },
  { id: "item-y2k-gamecube", face: "GameCube", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-gamecube.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-gamecube.webp") },
  { id: "item-y2k-ipod", face: "iPod", emotion: "Keepsake", gender: "m", style: "Y2K", neutral: true, source: require("@/assets/avatars/avatar-item-y2k-ipod.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-item-y2k-ipod.webp") },
];

// Generation-appropriate item avatars for migrating legacy face IDs.
// Each generation maps to one of its iconic nostalgic items.
const GENERATION_ITEM_AVATAR: Record<string, string> = {
  "20s": "item-20s-gramophone",
  "50s": "item-50s-jukebox",
  "70s": "item-70s-lavalamp",
  "80s": "item-80s-boombox",
  "90s": "item-90s-tamagotchi",
  "y2k": "item-y2k-mp3",
};

export function migrateLegacyAvatarId(id?: string, gender?: AvatarGender): string | undefined {
  if (!id) return undefined;
  if (AVATAR_DEFINITIONS.some((a) => a.id === id)) return id;
  // v1/v2 face avatars (smiley-*) -> generation-appropriate item avatar
  let match = id.match(/^smiley-(20s|50s|70s|80s|90s|y2k)-([1-8])(?:-[mf])?$/);
  if (match) return GENERATION_ITEM_AVATAR[match[1]];
  // original animal avatars -> generation item, same generation
  match = id.match(/^([a-z]+)-[mf](?:-(20s|50s|70s|80s|y2k))?$/);
  if (!match) return undefined;
  const suffix = match[2] ?? "90s";
  return GENERATION_ITEM_AVATAR[suffix] ?? "item-90s-tamagotchi";
}
export const SHINY_AVATARS = {
  "bull-shiny": require("@/assets/avatars/shiny/avatar-bull-shiny.webp"),
  "camel-shiny": require("@/assets/avatars/shiny/avatar-camel-shiny.webp"),
  "dove-shiny": require("@/assets/avatars/shiny/avatar-dove-shiny.webp"),
  "dragon-shiny": require("@/assets/avatars/shiny/avatar-dragon-shiny.webp"),
  "eagle-shiny": require("@/assets/avatars/shiny/avatar-eagle-shiny.webp"),
  "fox-shiny": require("@/assets/avatars/shiny/avatar-fox-shiny.webp"),
  "kangaroo-shiny": require("@/assets/avatars/shiny/avatar-kangaroo-shiny.webp"),
  "lion-shiny": require("@/assets/avatars/shiny/avatar-lion-shiny.webp"),
  "owl-shiny": require("@/assets/avatars/shiny/avatar-owl-shiny.webp"),
  "parrot-shiny": require("@/assets/avatars/shiny/avatar-parrot-shiny.webp"),
  "prayercircle-shiny": require("@/assets/avatars/shiny/avatar-prayercircle-shiny.webp"),
  "tiger-shiny": require("@/assets/avatars/shiny/avatar-tiger-shiny.webp"),
  "upper-room-shiny": require("@/assets/avatars/shiny/avatar-upper-room-shiny.webp"),
  "carmels-fire-shiny": require("@/assets/avatars/shiny/avatar-carmels-fire-shiny.webp"),
  "nehemiahs-watch-shiny": require("@/assets/avatars/shiny/avatar-nehemiahs-watch-shiny.webp"),
  "midnight-hymn-shiny": require("@/assets/avatars/shiny/avatar-midnight-hymn-shiny.webp"),
  "wilderness-prayer-shiny": require("@/assets/avatars/shiny/avatar-wilderness-prayer-shiny.webp"),
  "lords-prayer-shiny": require("@/assets/avatars/shiny/avatar-lords-prayer-shiny.webp"),
  "cloud-witnesses-shiny": require("@/assets/avatars/shiny/avatar-cloud-witnesses-shiny.webp"),
  "esthers-courage-shiny": require("@/assets/avatars/shiny/avatar-esthers-courage-shiny.webp"),
  "daniels-resolve-shiny": require("@/assets/avatars/shiny/avatar-daniels-resolve-shiny.webp"),
  "ninevehs-mercy-shiny": require("@/assets/avatars/shiny/avatar-ninevehs-mercy-shiny.webp"),
  "elijahs-strength-shiny": require("@/assets/avatars/shiny/avatar-elijahs-strength-shiny.webp"),
  "sinais-glory-shiny": require("@/assets/avatars/shiny/avatar-sinais-glory-shiny.webp"),
  "paul-apostle-shiny": require("@/assets/avatars/shiny/avatar-paul-apostle-shiny.webp"),
  "daniel-shiny": require("@/assets/avatars/shiny/avatar-daniel-shiny.webp"),
  "joseph-shiny": require("@/assets/avatars/shiny/avatar-joseph-shiny.webp"),
  "abraham-shiny": require("@/assets/avatars/shiny/avatar-abraham-shiny.webp"),
  "smiley-20s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-20s-shiny-cool.webp"),
  "smiley-20s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-20s-shiny-joy.webp"),
  "smiley-50s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-50s-shiny-cool.webp"),
  "smiley-50s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-50s-shiny-joy.webp"),
  "smiley-70s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-70s-shiny-cool.webp"),
  "smiley-70s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-70s-shiny-joy.webp"),
  "smiley-80s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-80s-shiny-cool.webp"),
  "smiley-80s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-80s-shiny-joy.webp"),
  "smiley-90s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-90s-shiny-cool.webp"),
  "smiley-90s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-90s-shiny-joy.webp"),
  "smiley-y2k-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-y2k-shiny-cool.webp"),
  "smiley-y2k-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-y2k-shiny-joy.webp"),
  "avatar-shiny-20s-reel": require("@/assets/avatars/shiny/avatar-shiny-20s-reel.webp"),
  "avatar-shiny-20s-zeppelin": require("@/assets/avatars/shiny/avatar-shiny-20s-zeppelin.webp"),
  "avatar-shiny-20s-crystalradio": require("@/assets/avatars/shiny/avatar-shiny-20s-crystalradio.webp"),
  "avatar-shiny-20s-mic": require("@/assets/avatars/shiny/avatar-shiny-20s-mic.webp"),
  "avatar-shiny-20s-locomotive": require("@/assets/avatars/shiny/avatar-shiny-20s-locomotive.webp"),
  "avatar-shiny-20s-clock": require("@/assets/avatars/shiny/avatar-shiny-20s-clock.webp"),
  "avatar-shiny-20s-speakeasy": require("@/assets/avatars/shiny/avatar-shiny-20s-speakeasy.webp"),
  "avatar-shiny-20s-auto": require("@/assets/avatars/shiny/avatar-shiny-20s-auto.webp"),
  "avatar-shiny-50s-drivein": require("@/assets/avatars/shiny/avatar-shiny-50s-drivein.webp"),
  "avatar-shiny-50s-diner": require("@/assets/avatars/shiny/avatar-shiny-50s-diner.webp"),
  "avatar-shiny-50s-rocket": require("@/assets/avatars/shiny/avatar-shiny-50s-rocket.webp"),
  "avatar-shiny-50s-saddleshoes": require("@/assets/avatars/shiny/avatar-shiny-50s-saddleshoes.webp"),
  "avatar-shiny-50s-hulahoop": require("@/assets/avatars/shiny/avatar-shiny-50s-hulahoop.webp"),
  "avatar-shiny-50s-transistor": require("@/assets/avatars/shiny/avatar-shiny-50s-transistor.webp"),
  "avatar-shiny-50s-convertible": require("@/assets/avatars/shiny/avatar-shiny-50s-convertible.webp"),
  "avatar-shiny-50s-maltshop": require("@/assets/avatars/shiny/avatar-shiny-50s-maltshop.webp"),
  "avatar-shiny-70s-vwbus": require("@/assets/avatars/shiny/avatar-shiny-70s-vwbus.webp"),
  "avatar-shiny-70s-platforms": require("@/assets/avatars/shiny/avatar-shiny-70s-platforms.webp"),
  "avatar-shiny-70s-8trackplayer": require("@/assets/avatars/shiny/avatar-shiny-70s-8trackplayer.webp"),
  "avatar-shiny-70s-waterbed": require("@/assets/avatars/shiny/avatar-shiny-70s-waterbed.webp"),
  "avatar-shiny-70s-beanbag": require("@/assets/avatars/shiny/avatar-shiny-70s-beanbag.webp"),
  "avatar-shiny-70s-macrame": require("@/assets/avatars/shiny/avatar-shiny-70s-macrame.webp"),
  "avatar-shiny-70s-rollerdisco": require("@/assets/avatars/shiny/avatar-shiny-70s-rollerdisco.webp"),
  "avatar-shiny-70s-calculator": require("@/assets/avatars/shiny/avatar-shiny-70s-calculator.webp"),
  "avatar-shiny-80s-vcr": require("@/assets/avatars/shiny/avatar-shiny-80s-vcr.webp"),
  "avatar-shiny-80s-neon": require("@/assets/avatars/shiny/avatar-shiny-80s-neon.webp"),
  "avatar-shiny-80s-delorean": require("@/assets/avatars/shiny/avatar-shiny-80s-delorean.webp"),
  "avatar-shiny-80s-boombox": require("@/assets/avatars/shiny/avatar-shiny-80s-boombox.webp"),
  "avatar-shiny-80s-cassette": require("@/assets/avatars/shiny/avatar-shiny-80s-cassette.webp"),
  "avatar-shiny-80s-brickphone": require("@/assets/avatars/shiny/avatar-shiny-80s-brickphone.webp"),
  "avatar-shiny-80s-laserdisc": require("@/assets/avatars/shiny/avatar-shiny-80s-laserdisc.webp"),
  "avatar-shiny-80s-keytar": require("@/assets/avatars/shiny/avatar-shiny-80s-keytar.webp"),
  "avatar-shiny-90s-modem": require("@/assets/avatars/shiny/avatar-shiny-90s-modem.webp"),
  "avatar-shiny-90s-snes": require("@/assets/avatars/shiny/avatar-shiny-90s-snes.webp"),
  "avatar-shiny-90s-beanie": require("@/assets/avatars/shiny/avatar-shiny-90s-beanie.webp"),
  "avatar-shiny-90s-pager": require("@/assets/avatars/shiny/avatar-shiny-90s-pager.webp"),
  "avatar-shiny-90s-cdplayer": require("@/assets/avatars/shiny/avatar-shiny-90s-cdplayer.webp"),
  "avatar-shiny-90s-inflate": require("@/assets/avatars/shiny/avatar-shiny-90s-inflate.webp"),
  "avatar-shiny-90s-troll": require("@/assets/avatars/shiny/avatar-shiny-90s-troll.webp"),
  "avatar-shiny-90s-gameboy": require("@/assets/avatars/shiny/avatar-shiny-90s-gameboy.webp"),
  "avatar-shiny-y2k-dvd": require("@/assets/avatars/shiny/avatar-shiny-y2k-dvd.webp"),
  "avatar-shiny-y2k-digicam": require("@/assets/avatars/shiny/avatar-shiny-y2k-digicam.webp"),
  "avatar-shiny-y2k-mp3": require("@/assets/avatars/shiny/avatar-shiny-y2k-mp3.webp"),
  "avatar-shiny-y2k-gelpen": require("@/assets/avatars/shiny/avatar-shiny-y2k-gelpen.webp"),
  "avatar-shiny-y2k-minidisc": require("@/assets/avatars/shiny/avatar-shiny-y2k-minidisc.webp"),
  "avatar-shiny-y2k-webcam": require("@/assets/avatars/shiny/avatar-shiny-y2k-webcam.webp"),
  "avatar-shiny-y2k-clips": require("@/assets/avatars/shiny/avatar-shiny-y2k-clips.webp"),
  "avatar-shiny-y2k-cdwallet": require("@/assets/avatars/shiny/avatar-shiny-y2k-cdwallet.webp"),
  "moses-shiny": require("@/assets/avatars/shiny/avatar-moses-shiny.webp"),
  "david-shiny": require("@/assets/avatars/shiny/avatar-david-shiny.webp"),
  "esther-shiny": require("@/assets/avatars/shiny/avatar-esther-shiny.webp"),
  "fish-loaves-shiny": require("@/assets/avatars/shiny/avatar-fish-loaves-shiny.webp"),
  "donkey-shiny": require("@/assets/avatars/shiny/avatar-donkey-shiny.webp"),
  "sheep-shiny": require("@/assets/avatars/shiny/avatar-sheep-shiny.webp"),
  "lion-judah-shiny": require("@/assets/avatars/shiny/avatar-lion-judah-shiny.webp"),
  "lamb-god-shiny": require("@/assets/avatars/shiny/avatar-lamb-god-shiny.webp"),
  "eagle-wings-shiny": require("@/assets/avatars/shiny/avatar-eagle-wings-shiny.webp"),
  "raven-provision-shiny": require("@/assets/avatars/shiny/avatar-raven-provision-shiny.webp"),
} as const;

export const SHINY_AVATAR_THUMBNAILS = {
  "bull-shiny": require("@/assets/avatars/thumbs/avatar-bull-shiny.webp"),
  "camel-shiny": require("@/assets/avatars/thumbs/avatar-camel-shiny.webp"),
  "dove-shiny": require("@/assets/avatars/thumbs/avatar-dove-shiny.webp"),
  "dragon-shiny": require("@/assets/avatars/thumbs/avatar-dragon-shiny.webp"),
  "eagle-shiny": require("@/assets/avatars/thumbs/avatar-eagle-shiny.webp"),
  "fox-shiny": require("@/assets/avatars/thumbs/avatar-fox-shiny.webp"),
  "kangaroo-shiny": require("@/assets/avatars/thumbs/avatar-kangaroo-shiny.webp"),
  "lion-shiny": require("@/assets/avatars/thumbs/avatar-lion-shiny.webp"),
  "owl-shiny": require("@/assets/avatars/thumbs/avatar-owl-shiny.webp"),
  "parrot-shiny": require("@/assets/avatars/thumbs/avatar-parrot-shiny.webp"),
  "prayercircle-shiny": require("@/assets/avatars/thumbs/avatar-prayercircle-shiny.webp"),
  "tiger-shiny": require("@/assets/avatars/thumbs/avatar-tiger-shiny.webp"),
  "upper-room-shiny": require("@/assets/avatars/shiny/avatar-upper-room-shiny.webp"),
  "carmels-fire-shiny": require("@/assets/avatars/shiny/avatar-carmels-fire-shiny.webp"),
  "nehemiahs-watch-shiny": require("@/assets/avatars/shiny/avatar-nehemiahs-watch-shiny.webp"),
  "midnight-hymn-shiny": require("@/assets/avatars/shiny/avatar-midnight-hymn-shiny.webp"),
  "wilderness-prayer-shiny": require("@/assets/avatars/shiny/avatar-wilderness-prayer-shiny.webp"),
  "lords-prayer-shiny": require("@/assets/avatars/shiny/avatar-lords-prayer-shiny.webp"),
  "cloud-witnesses-shiny": require("@/assets/avatars/shiny/avatar-cloud-witnesses-shiny.webp"),
  "esthers-courage-shiny": require("@/assets/avatars/shiny/avatar-esthers-courage-shiny.webp"),
  "daniels-resolve-shiny": require("@/assets/avatars/shiny/avatar-daniels-resolve-shiny.webp"),
  "ninevehs-mercy-shiny": require("@/assets/avatars/shiny/avatar-ninevehs-mercy-shiny.webp"),
  "elijahs-strength-shiny": require("@/assets/avatars/shiny/avatar-elijahs-strength-shiny.webp"),
  "sinais-glory-shiny": require("@/assets/avatars/shiny/avatar-sinais-glory-shiny.webp"),
  "paul-apostle-shiny": require("@/assets/avatars/shiny/avatar-paul-apostle-shiny.webp"),
  "daniel-shiny": require("@/assets/avatars/shiny/avatar-daniel-shiny.webp"),
  "joseph-shiny": require("@/assets/avatars/shiny/avatar-joseph-shiny.webp"),
  "abraham-shiny": require("@/assets/avatars/shiny/avatar-abraham-shiny.webp"),
  "moses-shiny": require("@/assets/avatars/shiny/avatar-moses-shiny.webp"),
  "david-shiny": require("@/assets/avatars/shiny/avatar-david-shiny.webp"),
  "esther-shiny": require("@/assets/avatars/shiny/avatar-esther-shiny.webp"),
  "fish-loaves-shiny": require("@/assets/avatars/shiny/avatar-fish-loaves-shiny.webp"),
  "donkey-shiny": require("@/assets/avatars/shiny/avatar-donkey-shiny.webp"),
  "sheep-shiny": require("@/assets/avatars/shiny/avatar-sheep-shiny.webp"),
  "lion-judah-shiny": require("@/assets/avatars/shiny/avatar-lion-judah-shiny.webp"),
  "lamb-god-shiny": require("@/assets/avatars/shiny/avatar-lamb-god-shiny.webp"),
  "eagle-wings-shiny": require("@/assets/avatars/shiny/avatar-eagle-wings-shiny.webp"),
  "raven-provision-shiny": require("@/assets/avatars/shiny/avatar-raven-provision-shiny.webp"),
  "smiley-20s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-20s-shiny-cool.webp"),
  "smiley-20s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-20s-shiny-joy.webp"),
  "smiley-50s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-50s-shiny-cool.webp"),
  "smiley-50s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-50s-shiny-joy.webp"),
  "smiley-70s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-70s-shiny-cool.webp"),
  "smiley-70s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-70s-shiny-joy.webp"),
  "smiley-80s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-80s-shiny-cool.webp"),
  "smiley-80s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-80s-shiny-joy.webp"),
  "smiley-90s-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-90s-shiny-cool.webp"),
  "smiley-90s-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-90s-shiny-joy.webp"),
  "smiley-y2k-shiny-cool": require("@/assets/avatars/shiny/avatar-smiley-y2k-shiny-cool.webp"),
  "smiley-y2k-shiny-joy": require("@/assets/avatars/shiny/avatar-smiley-y2k-shiny-joy.webp"),
  "avatar-shiny-20s-reel": require("@/assets/avatars/shiny/avatar-shiny-20s-reel.webp"),
  "avatar-shiny-20s-zeppelin": require("@/assets/avatars/shiny/avatar-shiny-20s-zeppelin.webp"),
  "avatar-shiny-20s-crystalradio": require("@/assets/avatars/shiny/avatar-shiny-20s-crystalradio.webp"),
  "avatar-shiny-20s-mic": require("@/assets/avatars/shiny/avatar-shiny-20s-mic.webp"),
  "avatar-shiny-20s-locomotive": require("@/assets/avatars/shiny/avatar-shiny-20s-locomotive.webp"),
  "avatar-shiny-20s-clock": require("@/assets/avatars/shiny/avatar-shiny-20s-clock.webp"),
  "avatar-shiny-20s-speakeasy": require("@/assets/avatars/shiny/avatar-shiny-20s-speakeasy.webp"),
  "avatar-shiny-20s-auto": require("@/assets/avatars/shiny/avatar-shiny-20s-auto.webp"),
  "avatar-shiny-50s-drivein": require("@/assets/avatars/shiny/avatar-shiny-50s-drivein.webp"),
  "avatar-shiny-50s-diner": require("@/assets/avatars/shiny/avatar-shiny-50s-diner.webp"),
  "avatar-shiny-50s-rocket": require("@/assets/avatars/shiny/avatar-shiny-50s-rocket.webp"),
  "avatar-shiny-50s-saddleshoes": require("@/assets/avatars/shiny/avatar-shiny-50s-saddleshoes.webp"),
  "avatar-shiny-50s-hulahoop": require("@/assets/avatars/shiny/avatar-shiny-50s-hulahoop.webp"),
  "avatar-shiny-50s-transistor": require("@/assets/avatars/shiny/avatar-shiny-50s-transistor.webp"),
  "avatar-shiny-50s-convertible": require("@/assets/avatars/shiny/avatar-shiny-50s-convertible.webp"),
  "avatar-shiny-50s-maltshop": require("@/assets/avatars/shiny/avatar-shiny-50s-maltshop.webp"),
  "avatar-shiny-70s-vwbus": require("@/assets/avatars/shiny/avatar-shiny-70s-vwbus.webp"),
  "avatar-shiny-70s-platforms": require("@/assets/avatars/shiny/avatar-shiny-70s-platforms.webp"),
  "avatar-shiny-70s-8trackplayer": require("@/assets/avatars/shiny/avatar-shiny-70s-8trackplayer.webp"),
  "avatar-shiny-70s-waterbed": require("@/assets/avatars/shiny/avatar-shiny-70s-waterbed.webp"),
  "avatar-shiny-70s-beanbag": require("@/assets/avatars/shiny/avatar-shiny-70s-beanbag.webp"),
  "avatar-shiny-70s-macrame": require("@/assets/avatars/shiny/avatar-shiny-70s-macrame.webp"),
  "avatar-shiny-70s-rollerdisco": require("@/assets/avatars/shiny/avatar-shiny-70s-rollerdisco.webp"),
  "avatar-shiny-70s-calculator": require("@/assets/avatars/shiny/avatar-shiny-70s-calculator.webp"),
  "avatar-shiny-80s-vcr": require("@/assets/avatars/shiny/avatar-shiny-80s-vcr.webp"),
  "avatar-shiny-80s-neon": require("@/assets/avatars/shiny/avatar-shiny-80s-neon.webp"),
  "avatar-shiny-80s-delorean": require("@/assets/avatars/shiny/avatar-shiny-80s-delorean.webp"),
  "avatar-shiny-80s-boombox": require("@/assets/avatars/shiny/avatar-shiny-80s-boombox.webp"),
  "avatar-shiny-80s-cassette": require("@/assets/avatars/shiny/avatar-shiny-80s-cassette.webp"),
  "avatar-shiny-80s-brickphone": require("@/assets/avatars/shiny/avatar-shiny-80s-brickphone.webp"),
  "avatar-shiny-80s-laserdisc": require("@/assets/avatars/shiny/avatar-shiny-80s-laserdisc.webp"),
  "avatar-shiny-80s-keytar": require("@/assets/avatars/shiny/avatar-shiny-80s-keytar.webp"),
  "avatar-shiny-90s-modem": require("@/assets/avatars/shiny/avatar-shiny-90s-modem.webp"),
  "avatar-shiny-90s-snes": require("@/assets/avatars/shiny/avatar-shiny-90s-snes.webp"),
  "avatar-shiny-90s-beanie": require("@/assets/avatars/shiny/avatar-shiny-90s-beanie.webp"),
  "avatar-shiny-90s-pager": require("@/assets/avatars/shiny/avatar-shiny-90s-pager.webp"),
  "avatar-shiny-90s-cdplayer": require("@/assets/avatars/shiny/avatar-shiny-90s-cdplayer.webp"),
  "avatar-shiny-90s-inflate": require("@/assets/avatars/shiny/avatar-shiny-90s-inflate.webp"),
  "avatar-shiny-90s-troll": require("@/assets/avatars/shiny/avatar-shiny-90s-troll.webp"),
  "avatar-shiny-90s-gameboy": require("@/assets/avatars/shiny/avatar-shiny-90s-gameboy.webp"),
  "avatar-shiny-y2k-dvd": require("@/assets/avatars/shiny/avatar-shiny-y2k-dvd.webp"),
  "avatar-shiny-y2k-digicam": require("@/assets/avatars/shiny/avatar-shiny-y2k-digicam.webp"),
  "avatar-shiny-y2k-mp3": require("@/assets/avatars/shiny/avatar-shiny-y2k-mp3.webp"),
  "avatar-shiny-y2k-gelpen": require("@/assets/avatars/shiny/avatar-shiny-y2k-gelpen.webp"),
  "avatar-shiny-y2k-minidisc": require("@/assets/avatars/shiny/avatar-shiny-y2k-minidisc.webp"),
  "avatar-shiny-y2k-webcam": require("@/assets/avatars/shiny/avatar-shiny-y2k-webcam.webp"),
  "avatar-shiny-y2k-clips": require("@/assets/avatars/shiny/avatar-shiny-y2k-clips.webp"),
  "avatar-shiny-y2k-cdwallet": require("@/assets/avatars/shiny/avatar-shiny-y2k-cdwallet.webp"),
} as const;

export const HERO_AVATARS = {
  "david-hero": require("@/assets/avatars/heroes/avatar-david-hero.webp"),
  "moses-hero": require("@/assets/avatars/heroes/avatar-moses-hero.webp"),
  "paul-hero": require("@/assets/avatars/heroes/avatar-paul-hero.webp"),
  "peter-hero": require("@/assets/avatars/heroes/avatar-peter-hero.webp"),
  "esther-hero": require("@/assets/avatars/heroes/avatar-esther-hero.webp"),
  "daniel-hero": require("@/assets/avatars/heroes/avatar-daniel-hero.webp"),
  "spurgeon-hero": require("@/assets/avatars/heroes/avatar-spurgeon-hero.webp"),
  "moody-hero": require("@/assets/avatars/heroes/avatar-moody-hero.webp"),
  "noah-hero": require("@/assets/avatars/heroes/avatar-noah-hero.webp"),
  "elijah-hero": require("@/assets/avatars/heroes/avatar-elijah-hero.webp"),
  "samuel-hero": require("@/assets/avatars/heroes/avatar-samuel-hero.webp"),
  "ruth-hero": require("@/assets/avatars/heroes/avatar-ruth-hero.webp"),
  "johnbaptist-hero": require("@/assets/avatars/heroes/avatar-johnbaptist-hero.webp"),
  "mary-hero": require("@/assets/avatars/heroes/avatar-mary-hero.webp"),
  "luther-hero": require("@/assets/avatars/heroes/avatar-luther-hero.webp"),
  "corrie-hero": require("@/assets/avatars/heroes/avatar-corrie-hero.webp"),
} as const;

export const SHINY_HERO_AVATARS = {
  "jesus-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-jesus-shiny-hero.webp"),
  "abraham-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-abraham-shiny-hero.webp"),
  "joseph-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-joseph-shiny-hero.webp"),
  "david-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-david-shiny-hero.webp"),
} as const;

export type ShinyHeroAvatarId = keyof typeof SHINY_HERO_AVATARS;

export type HeroAvatarId = keyof typeof HERO_AVATARS;

export const HERO_ACHIEVEMENTS = [
  { id: "evo-david-3", name: "David", hint: "Reach a 30-day prayer streak", avatarId: "david-hero", title: "David the King" },
  { id: "fast-40", name: "Moses", hint: "Complete a 40-day fast", avatarId: "moses-hero", title: "Moses" },
  { id: "evo-paul-3", name: "Paul", hint: "Reach a 50-day prayer streak", avatarId: "paul-hero", title: "Paul the Apostle" },
  { id: "evo-peter-3", name: "Peter", hint: "Complete a 30-day fast", avatarId: "peter-hero", title: "Peter the Restored" },
  { id: "fast-5", name: "Esther", hint: "Complete a 5-day fast", avatarId: "esther-hero", title: "Esther" },
  { id: "fast-10", name: "Daniel", hint: "Complete a 10-day fast", avatarId: "daniel-hero", title: "Daniel" },
  { id: "fast-100", name: "Spurgeon", hint: "Complete a 100-day fast", avatarId: "spurgeon-hero", title: "Charles Spurgeon" },
  { id: "streak-100", name: "Moody", hint: "Reach a 100-day prayer streak", avatarId: "moody-hero", title: "D.L. Moody" },
  { id: "fast-7", name: "Noah", hint: "Complete a 7-day fast", avatarId: "noah-hero", title: "Noah the Ark Builder" },
  { id: "fast-21", name: "Elijah", hint: "Complete a 21-day fast", avatarId: "elijah-hero", title: "Elijah the Prophet" },
  { id: "streak-15", name: "Samuel", hint: "Reach a 15-day prayer streak", avatarId: "samuel-hero", title: "Samuel the Prophet" },
  { id: "streak-7", name: "Ruth", hint: "Reach a 7-day prayer streak", avatarId: "ruth-hero", title: "Ruth the Loyal" },
  { id: "fast-30", name: "John the Baptist", hint: "Complete a 30-day fast", avatarId: "johnbaptist-hero", title: "John the Baptist" },
  { id: "streak-25", name: "Mary", hint: "Reach a 25-day prayer streak", avatarId: "mary-hero", title: "Mary the Mother" },
  { id: "streak-50", name: "Luther", hint: "Reach a 50-day prayer streak", avatarId: "luther-hero", title: "Martin Luther" },
  { id: "fast-60", name: "Corrie", hint: "Complete a 60-day fast", avatarId: "corrie-hero", title: "Corrie ten Boom" },
] as const;

export type ShinyAvatarId = keyof typeof SHINY_AVATARS;

export const SHINY_ACHIEVEMENTS = [
  { id: "first-task", name: "Dawn Lion", hint: "Schedule your first task", avatarId: "lion-shiny", title: "First Task" },
  { id: "full-set", name: "Triune Dragon", hint: "Schedule one task of each type", avatarId: "dragon-shiny", title: "Full Set" },
  { id: "curator", name: "Psalm Parrot", hint: "Save your first album", avatarId: "parrot-shiny", title: "Curator" },
  { id: "streak-5", name: "Upper Room", hint: "Reach a 5-day prayer streak", avatarId: "upper-room-shiny", title: "5-Day Streak" },
  { id: "streak-7", name: "Ember Fox", hint: "Reach a 7-day prayer streak", avatarId: "fox-shiny", title: "7-Day Streak" },
  { id: "streak-10", name: "Carmel's Fire", hint: "Reach a 10-day prayer streak", avatarId: "carmels-fire-shiny", title: "10-Day Streak" },
  { id: "streak-15", name: "Nehemiah's Watch", hint: "Reach a 15-day prayer streak", avatarId: "nehemiahs-watch-shiny", title: "15-Day Streak" },
  { id: "streak-20", name: "Midnight Hymn", hint: "Reach a 20-day prayer streak", avatarId: "midnight-hymn-shiny", title: "20-Day Streak" },
  { id: "streak-21", name: "Covenant Eagle", hint: "Reach a 21-day prayer streak", avatarId: "eagle-shiny", title: "21-Day Streak" },
  { id: "streak-25", name: "Wilderness Prayer", hint: "Reach a 25-day prayer streak", avatarId: "wilderness-prayer-shiny", title: "25-Day Streak" },
  { id: "streak-30", name: "The Lord's Prayer", hint: "Reach a 30-day prayer streak", title: "30-Day Streak" },
  { id: "streak-75", name: "Cloud of Witnesses", hint: "Reach a 75-day prayer streak", avatarId: "cloud-witnesses-shiny", title: "75-Day Streak" },
  { id: "fast-5", name: "Esther's Courage", hint: "Complete a 5-day fast", avatarId: "esthers-courage-shiny", title: "5-Day Fast" },
  { id: "fast-7", name: "Desert Camel", hint: "Complete a 7-day fast", avatarId: "camel-shiny", title: "7-Day Fast" },
  { id: "fast-10", name: "Daniel's Resolve", hint: "Complete a 10-day fast", avatarId: "daniels-resolve-shiny", title: "10-Day Fast" },
  { id: "fast-15", name: "Nineveh's Mercy", hint: "Complete a 15-day fast", avatarId: "ninevehs-mercy-shiny", title: "15-Day Fast" },
  { id: "fast-20", name: "Elijah's Strength", hint: "Complete a 20-day fast", avatarId: "elijahs-strength-shiny", title: "20-Day Fast" },
  { id: "fast-21", name: "Manna Dove", hint: "Complete a 21-day fast", avatarId: "dove-shiny", title: "21-Day Fast" },
  { id: "fast-25", name: "Sinai's Glory", hint: "Complete a 25-day fast", avatarId: "sinais-glory-shiny", title: "25-Day Fast" },
  { id: "fast-30", name: "Temptation's End", hint: "Complete a 30-day fast", title: "30-Day Fast" },
  { id: "fast-60", name: "Intercession", hint: "Complete a 60-day fast", title: "60-Day Fast" },
  { id: "evo-david-1", name: "David the Shepherd", hint: "Reach a 5-day prayer streak", title: "David: Stage 1" },
  { id: "evo-david-2", name: "David the Giant Slayer", hint: "Reach a 15-day prayer streak", title: "David: Stage 2" },
  { id: "evo-david-3", name: "David the King", hint: "Reach a 30-day prayer streak", title: "David: Stage 3" },
  { id: "evo-peter-1", name: "Peter the Fisherman", hint: "Complete a 5-day fast", title: "Peter: Stage 1" },
  { id: "evo-peter-2", name: "Peter the Denier", hint: "Complete a 15-day fast", title: "Peter: Stage 2" },
  { id: "evo-peter-3", name: "Peter the Restored", hint: "Complete a 30-day fast", title: "Peter: Stage 3" },
  { id: "evo-paul-1", name: "Saul the Persecutor", hint: "Reach a 10-day prayer streak", title: "Paul: Stage 1" },
  { id: "evo-paul-2", name: "Saul the Blinded", hint: "Reach a 20-day prayer streak", title: "Paul: Stage 2" },
  { id: "evo-paul-3", name: "Paul the Apostle", hint: "Reach a 50-day prayer streak", title: "Paul: Stage 3" },
  { id: "streak-50", name: "Burning Bush Tiger", hint: "Reach a 50-day prayer streak", avatarId: "tiger-shiny", title: "50-Day Streak" },
  { id: "streak-100", name: "Heavens Owl", hint: "Reach a 100-day prayer streak", avatarId: "owl-shiny", title: "100-Day Streak" },
  { id: "fast-40", name: "Wilderness Kangaroo", hint: "Complete a 40-day fast", avatarId: "kangaroo-shiny", title: "40-Day Fast" },
  { id: "fast-100", name: "Armor of God Bull", hint: "Complete a 100-day fast", avatarId: "bull-shiny", title: "100-Day Fast" },
  { id: "fast-365", name: "Mr. Prayer Circle", hint: "Complete a 365-day fast", avatarId: "prayercircle-shiny", title: "365-Day Fast" },
  { id: "streak-100", name: "Jesus", hint: "Reach a 100-day prayer streak", avatarId: "jesus-shiny-hero", title: "Jesus" },
  { id: "fast-60", name: "Abraham", hint: "Complete a 60-day fast", avatarId: "abraham-shiny-hero", title: "Abraham" },
  { id: "fast-30", name: "Joseph", hint: "Complete a 30-day fast", avatarId: "joseph-shiny-hero", title: "Joseph" },
  { id: "streak-30", name: "David", hint: "Reach a 30-day prayer streak", avatarId: "david-shiny-hero", title: "David" },
  { id: "shiny-manna-dawn", name: "Manna Dove: Dawn", hint: "Complete a 21-day fast", title: "Manna Dawn" },
  { id: "shiny-manna-evening", name: "Manna Dove: Evening", hint: "Complete a 25-day fast", title: "Manna Evening" },
  { id: "shiny-carmel-fire", name: "Elijah: Carmel's Fire", hint: "Reach a 35-day prayer streak", title: "Carmel Fire" },
  { id: "shiny-whirlwind", name: "Elijah: Whirlwind", hint: "Reach a 40-day prayer streak", title: "Whirlwind" },
  { id: "shiny-abraham-starry", name: "Abraham: Starry Sky", hint: "Reach a 45-day prayer streak", avatarId: "abraham-shiny", title: "Starry Sky" },
  { id: "shiny-moses-bush", name: "Moses: Burning Bush", hint: "Complete a 45-day fast", avatarId: "moses-shiny", title: "Burning Bush" },
  { id: "shiny-david-harp", name: "David: Harp", hint: "Reach a 60-day prayer streak", avatarId: "david-shiny", title: "David's Harp" },
  { id: "shiny-esther-crown", name: "Esther: Crown", hint: "Complete a 60-day fast", avatarId: "esther-shiny", title: "Esther's Crown" },
  { id: "shiny-lion-judah", name: "Lion of Judah", hint: "Reach a 75-day prayer streak", avatarId: "lion-judah-shiny", title: "Lion of Judah" },
  { id: "shiny-lamb-god", name: "Lamb of God", hint: "Complete a 75-day fast", avatarId: "lamb-god-shiny", title: "Lamb of God" },
  { id: "shiny-eagle-wings", name: "Eagle's Wings", hint: "Reach a 90-day prayer streak", avatarId: "eagle-wings-shiny", title: "Eagle's Wings" },
  { id: "shiny-raven-elijah", name: "Raven's Provision", hint: "Complete a 90-day fast", avatarId: "raven-provision-shiny", title: "Raven's Provision" },
  { id: "shiny-paul-dove", name: "Paul: Inspired", hint: "Reach a 100-day prayer streak", title: "Paul Inspired" },
  { id: "shiny-daniel-dove", name: "Daniel: Protected", hint: "Complete a 100-day fast", title: "Daniel Protected" },
  { id: "shiny-joseph-dove", name: "Joseph: Dreamer", hint: "Reach a 120-day prayer streak", title: "Joseph Dreamer" },
  { id: "shiny-fish-loaves", name: "Loaves & Fishes", hint: "Complete a 120-day fast", title: "Loaves & Fishes" },
  { id: "shiny-donkey-triumph", name: "Triumphal Donkey", hint: "Reach a 150-day prayer streak", title: "Triumphal Donkey" },
  { id: "shiny-sheep-shepherd", name: "The Lost Sheep", hint: "Complete a 150-day fast", title: "Lost Sheep" },
  { id: "smiley-20s-shiny-cool", name: "Art Deco Skyscraper", hint: "Reach a 10-day prayer streak", avatarId: "smiley-20s-shiny-cool", title: "Art Deco Skyscraper" },
  { id: "smiley-20s-shiny-joy", name: "Jazz Trumpet", hint: "Reach a 15-day prayer streak", avatarId: "smiley-20s-shiny-joy", title: "Jazz Trumpet" },
  { id: "avatar-shiny-20s-reel", name: "Silent Film Reel", hint: "Reach a 20-day prayer streak", avatarId: "avatar-shiny-20s-reel", title: "Silent Film Reel" },
  { id: "avatar-shiny-20s-zeppelin", name: "Zeppelin Airship", hint: "Reach a 25-day prayer streak", avatarId: "avatar-shiny-20s-zeppelin", title: "Zeppelin Airship" },
  { id: "avatar-shiny-20s-crystalradio", name: "Crystal Radio", hint: "Reach a 30-day prayer streak", avatarId: "avatar-shiny-20s-crystalradio", title: "Crystal Radio" },
  { id: "avatar-shiny-20s-mic", name: "Vintage Microphone", hint: "Reach a 35-day prayer streak", avatarId: "avatar-shiny-20s-mic", title: "Vintage Microphone" },
  { id: "avatar-shiny-20s-locomotive", name: "Steam Locomotive", hint: "Reach a 40-day prayer streak", avatarId: "avatar-shiny-20s-locomotive", title: "Steam Locomotive" },
  { id: "avatar-shiny-20s-clock", name: "Art Deco Clock", hint: "Reach a 45-day prayer streak", avatarId: "avatar-shiny-20s-clock", title: "Art Deco Clock" },
  { id: "avatar-shiny-20s-speakeasy", name: "Speakeasy Door", hint: "Reach a 50-day prayer streak", avatarId: "avatar-shiny-20s-speakeasy", title: "Speakeasy Door" },
  { id: "avatar-shiny-20s-auto", name: "Luxury Automobile", hint: "Reach a 55-day prayer streak", avatarId: "avatar-shiny-20s-auto", title: "Luxury Automobile" },
  { id: "smiley-50s-shiny-cool", name: "Jukebox", hint: "Reach a 60-day prayer streak", avatarId: "smiley-50s-shiny-cool", title: "Jukebox" },
  { id: "smiley-50s-shiny-joy", name: "Classic Car Tailfin", hint: "Reach a 65-day prayer streak", avatarId: "smiley-50s-shiny-joy", title: "Classic Car Tailfin" },
  { id: "avatar-shiny-50s-drivein", name: "Drive-In Sign", hint: "Reach a 70-day prayer streak", avatarId: "avatar-shiny-50s-drivein", title: "Drive-In Sign" },
  { id: "avatar-shiny-50s-diner", name: "Chrome Diner", hint: "Reach a 75-day prayer streak", avatarId: "avatar-shiny-50s-diner", title: "Chrome Diner" },
  { id: "avatar-shiny-50s-rocket", name: "Rocket Ship", hint: "Reach a 80-day prayer streak", avatarId: "avatar-shiny-50s-rocket", title: "Rocket Ship" },
  { id: "avatar-shiny-50s-saddleshoes", name: "Saddle Shoes", hint: "Reach a 85-day prayer streak", avatarId: "avatar-shiny-50s-saddleshoes", title: "Saddle Shoes" },
  { id: "avatar-shiny-50s-hulahoop", name: "Hula Hoop", hint: "Reach a 90-day prayer streak", avatarId: "avatar-shiny-50s-hulahoop", title: "Hula Hoop" },
  { id: "avatar-shiny-50s-transistor", name: "Transistor Radio", hint: "Reach a 95-day prayer streak", avatarId: "avatar-shiny-50s-transistor", title: "Transistor Radio" },
  { id: "avatar-shiny-50s-convertible", name: "Convertible", hint: "Reach a 100-day prayer streak", avatarId: "avatar-shiny-50s-convertible", title: "Convertible" },
  { id: "avatar-shiny-50s-maltshop", name: "Malt Shop", hint: "Reach a 105-day prayer streak", avatarId: "avatar-shiny-50s-maltshop", title: "Malt Shop" },
  { id: "smiley-70s-shiny-cool", name: "Disco Ball", hint: "Reach a 110-day prayer streak", avatarId: "smiley-70s-shiny-cool", title: "Disco Ball" },
  { id: "smiley-70s-shiny-joy", name: "Vinyl Record", hint: "Reach a 115-day prayer streak", avatarId: "smiley-70s-shiny-joy", title: "Vinyl Record" },
  { id: "avatar-shiny-70s-vwbus", name: "VW Bus", hint: "Reach a 120-day prayer streak", avatarId: "avatar-shiny-70s-vwbus", title: "VW Bus" },
  { id: "avatar-shiny-70s-platforms", name: "Platform Shoes", hint: "Reach a 125-day prayer streak", avatarId: "avatar-shiny-70s-platforms", title: "Platform Shoes" },
  { id: "avatar-shiny-70s-8trackplayer", name: "8-Track Player", hint: "Reach a 130-day prayer streak", avatarId: "avatar-shiny-70s-8trackplayer", title: "8-Track Player" },
  { id: "avatar-shiny-70s-waterbed", name: "Waterbed", hint: "Reach a 135-day prayer streak", avatarId: "avatar-shiny-70s-waterbed", title: "Waterbed" },
  { id: "avatar-shiny-70s-beanbag", name: "Beanbag Chair", hint: "Reach a 140-day prayer streak", avatarId: "avatar-shiny-70s-beanbag", title: "Beanbag Chair" },
  { id: "avatar-shiny-70s-macrame", name: "Macrame Owl", hint: "Reach a 145-day prayer streak", avatarId: "avatar-shiny-70s-macrame", title: "Macrame Owl" },
  { id: "avatar-shiny-70s-rollerdisco", name: "Roller Disco", hint: "Reach a 150-day prayer streak", avatarId: "avatar-shiny-70s-rollerdisco", title: "Roller Disco" },
  { id: "avatar-shiny-70s-calculator", name: "Pocket Calculator", hint: "Reach a 155-day prayer streak", avatarId: "avatar-shiny-70s-calculator", title: "Pocket Calculator" },
  { id: "smiley-80s-shiny-cool", name: "Walkman", hint: "Reach a 160-day prayer streak", avatarId: "smiley-80s-shiny-cool", title: "Walkman" },
  { id: "smiley-80s-shiny-joy", name: "Arcade Cabinet", hint: "Reach a 165-day prayer streak", avatarId: "smiley-80s-shiny-joy", title: "Arcade Cabinet" },
  { id: "avatar-shiny-80s-vcr", name: "VCR", hint: "Reach a 170-day prayer streak", avatarId: "avatar-shiny-80s-vcr", title: "VCR" },
  { id: "avatar-shiny-80s-neon", name: "Neon Sign", hint: "Reach a 175-day prayer streak", avatarId: "avatar-shiny-80s-neon", title: "Neon Sign" },
  { id: "avatar-shiny-80s-delorean", name: "DeLorean", hint: "Reach a 180-day prayer streak", avatarId: "avatar-shiny-80s-delorean", title: "DeLorean" },
  { id: "avatar-shiny-80s-boombox", name: "Holographic Boombox", hint: "Reach a 185-day prayer streak", avatarId: "avatar-shiny-80s-boombox", title: "Holographic Boombox" },
  { id: "avatar-shiny-80s-cassette", name: "Holographic Cassette", hint: "Reach a 190-day prayer streak", avatarId: "avatar-shiny-80s-cassette", title: "Holographic Cassette" },
  { id: "avatar-shiny-80s-brickphone", name: "Brick Phone", hint: "Reach a 195-day prayer streak", avatarId: "avatar-shiny-80s-brickphone", title: "Brick Phone" },
  { id: "avatar-shiny-80s-laserdisc", name: "LaserDisc", hint: "Reach a 200-day prayer streak", avatarId: "avatar-shiny-80s-laserdisc", title: "LaserDisc" },
  { id: "avatar-shiny-80s-keytar", name: "Keytar", hint: "Reach a 205-day prayer streak", avatarId: "avatar-shiny-80s-keytar", title: "Keytar" },
  { id: "smiley-90s-shiny-cool", name: "Floppy Disk", hint: "Reach a 210-day prayer streak", avatarId: "smiley-90s-shiny-cool", title: "Floppy Disk" },
  { id: "smiley-90s-shiny-joy", name: "CRT Monitor", hint: "Reach a 215-day prayer streak", avatarId: "smiley-90s-shiny-joy", title: "CRT Monitor" },
  { id: "avatar-shiny-90s-modem", name: "Dial-Up Modem", hint: "Reach a 220-day prayer streak", avatarId: "avatar-shiny-90s-modem", title: "Dial-Up Modem" },
  { id: "avatar-shiny-90s-snes", name: "SNES Controller", hint: "Reach a 225-day prayer streak", avatarId: "avatar-shiny-90s-snes", title: "SNES Controller" },
  { id: "avatar-shiny-90s-beanie", name: "Beanie Baby", hint: "Reach a 230-day prayer streak", avatarId: "avatar-shiny-90s-beanie", title: "Beanie Baby" },
  { id: "avatar-shiny-90s-pager", name: "Holographic Pager", hint: "Reach a 235-day prayer streak", avatarId: "avatar-shiny-90s-pager", title: "Holographic Pager" },
  { id: "avatar-shiny-90s-cdplayer", name: "CD Player", hint: "Reach a 240-day prayer streak", avatarId: "avatar-shiny-90s-cdplayer", title: "CD Player" },
  { id: "avatar-shiny-90s-inflate", name: "Holographic Inflatable Chair", hint: "Reach a 245-day prayer streak", avatarId: "avatar-shiny-90s-inflate", title: "Holographic Inflatable Chair" },
  { id: "avatar-shiny-90s-troll", name: "Holographic Troll Doll", hint: "Reach a 250-day prayer streak", avatarId: "avatar-shiny-90s-troll", title: "Holographic Troll Doll" },
  { id: "avatar-shiny-90s-gameboy", name: "Holographic Game Boy", hint: "Reach a 255-day prayer streak", avatarId: "avatar-shiny-90s-gameboy", title: "Holographic Game Boy" },
  { id: "smiley-y2k-shiny-cool", name: "Flip Phone", hint: "Reach a 260-day prayer streak", avatarId: "smiley-y2k-shiny-cool", title: "Flip Phone" },
  { id: "smiley-y2k-shiny-joy", name: "Candy Computer", hint: "Reach a 265-day prayer streak", avatarId: "smiley-y2k-shiny-joy", title: "Candy Computer" },
  { id: "avatar-shiny-y2k-dvd", name: "DVD Player", hint: "Reach a 270-day prayer streak", avatarId: "avatar-shiny-y2k-dvd", title: "DVD Player" },
  { id: "avatar-shiny-y2k-digicam", name: "Digital Camera", hint: "Reach a 275-day prayer streak", avatarId: "avatar-shiny-y2k-digicam", title: "Digital Camera" },
  { id: "avatar-shiny-y2k-mp3", name: "Holographic MP3 Player", hint: "Reach a 280-day prayer streak", avatarId: "avatar-shiny-y2k-mp3", title: "Holographic MP3 Player" },
  { id: "avatar-shiny-y2k-gelpen", name: "Holographic Gel Pens", hint: "Reach a 285-day prayer streak", avatarId: "avatar-shiny-y2k-gelpen", title: "Holographic Gel Pens" },
  { id: "avatar-shiny-y2k-minidisc", name: "MiniDisc Player", hint: "Reach a 290-day prayer streak", avatarId: "avatar-shiny-y2k-minidisc", title: "MiniDisc Player" },
  { id: "avatar-shiny-y2k-webcam", name: "Holographic Webcam", hint: "Reach a 295-day prayer streak", avatarId: "avatar-shiny-y2k-webcam", title: "Holographic Webcam" },
  { id: "avatar-shiny-y2k-clips", name: "Holographic Butterfly Clips", hint: "Reach a 300-day prayer streak", avatarId: "avatar-shiny-y2k-clips", title: "Holographic Butterfly Clips" },
  { id: "avatar-shiny-y2k-cdwallet", name: "Holographic CD Wallet", hint: "Reach a 305-day prayer streak", avatarId: "avatar-shiny-y2k-cdwallet", title: "Holographic CD Wallet" },
] as const;
export type AchievementId = (typeof SHINY_ACHIEVEMENTS)[number]["id"];

const STYLE_ORDER: AvatarStyle[] = ["1920s", "1950s", "1970s", "1980s", "90s", "Y2K"];
export { STYLE_ORDER };

export function avatarDefinitionById(id?: string, gender?: AvatarGender) {
  const direct = AVATAR_DEFINITIONS.find((avatar) => avatar.id === id);
  if (direct) return direct;
  const migrated = migrateLegacyAvatarId(id, gender);
  return migrated ? AVATAR_DEFINITIONS.find((avatar) => avatar.id === migrated) : undefined;
}

export function getAvatarDefinitionForPerson(id: string, gender?: AvatarGender, avatarAsset?: string) {
  const selected = avatarDefinitionById(avatarAsset, gender);
  // Keep the original initials circle until the user explicitly chooses a
  // bundled avatar. The arguments remain in this API for caller compatibility.
  void id;
  return selected;
}

export function getAvatarAssetForPerson(id: string, gender?: AvatarGender, avatarAsset?: string) {
  return getAvatarDefinitionForPerson(id, gender, avatarAsset)?.id;
}
