import type { ImageSourcePropType } from "react-native";

export type AvatarGender = "m" | "f";
export type AvatarStyle = "90s" | "1920s" | "1950s" | "1970s" | "1980s" | "Y2K";

export type AvatarDefinition = { id: string; animal: string; gender: AvatarGender; style: AvatarStyle; source: ImageSourcePropType; thumbnail: ImageSourcePropType };

export const AVATAR_DEFINITIONS: AvatarDefinition[] = [
  { id: "bat-m", animal: "bat", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-bat-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m.webp") },
  { id: "bear-m", animal: "bear", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-bear-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m.webp") },
  { id: "bee-f", animal: "bee", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-bee-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f.webp") },
  { id: "bull-m", animal: "bull", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-bull-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m.webp") },
  { id: "butterfly-f", animal: "butterfly", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-butterfly-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f.webp") },
  { id: "cat-f", animal: "cat", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-cat-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f.webp") },
  { id: "chameleon-m", animal: "chameleon", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-chameleon-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m.webp") },
  { id: "crab-m", animal: "crab", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-crab-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m.webp") },
  { id: "crocodile-m", animal: "crocodile", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-crocodile-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m.webp") },
  { id: "deer-m", animal: "deer", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-deer-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m.webp") },
  { id: "dog-m", animal: "dog", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-dog-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m.webp") },
  { id: "dolphin-f", animal: "dolphin", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-dolphin-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f.webp") },
  { id: "dragon-m", animal: "dragon", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-dragon-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m.webp") },
  { id: "eagle-m", animal: "eagle", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-eagle-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m.webp") },
  { id: "elephant-m", animal: "elephant", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-elephant-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m.webp") },
  { id: "flamingo-f", animal: "flamingo", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-flamingo-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f.webp") },
  { id: "fox-f", animal: "fox", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-fox-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f.webp") },
  { id: "frog-f", animal: "frog", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-frog-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f.webp") },
  { id: "giraffe-f", animal: "giraffe", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-giraffe-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f.webp") },
  { id: "goat-m", animal: "goat", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-goat-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m.webp") },
  { id: "gorilla-m", animal: "gorilla", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-gorilla-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m.webp") },
  { id: "hamster-f", animal: "hamster", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-hamster-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f.webp") },
  { id: "hedgehog-f", animal: "hedgehog", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-hedgehog-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f.webp") },
  { id: "hippo-m", animal: "hippo", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-hippo-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m.webp") },
  { id: "horse-m", animal: "horse", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-horse-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m.webp") },
  { id: "jellyfish-f", animal: "jellyfish", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-jellyfish-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f.webp") },
  { id: "kangaroo-m", animal: "kangaroo", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-kangaroo-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m.webp") },
  { id: "koala-f", animal: "koala", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-koala-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f.webp") },
  { id: "lion-m", animal: "lion", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-lion-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m.webp") },
  { id: "llama-f", animal: "llama", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-llama-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f.webp") },
  { id: "monkey-m", animal: "monkey", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-monkey-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m.webp") },
  { id: "octopus-f", animal: "octopus", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-octopus-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f.webp") },
  { id: "owl-m", animal: "owl", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-owl-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m.webp") },
  { id: "panda-f", animal: "panda", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-panda-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f.webp") },
  { id: "parrot-f", animal: "parrot", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-parrot-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f.webp") },
  { id: "penguin-f", animal: "penguin", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-penguin-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f.webp") },
  { id: "pig-f", animal: "pig", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-pig-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f.webp") },
  { id: "rabbit-f", animal: "rabbit", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-rabbit-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f.webp") },
  { id: "raccoon-f", animal: "raccoon", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-raccoon-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f.webp") },
  { id: "rhino-m", animal: "rhino", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-rhino-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m.webp") },
  { id: "seahorse-f", animal: "seahorse", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-seahorse-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f.webp") },
  { id: "shark-m", animal: "shark", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-shark-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m.webp") },
  { id: "sloth-m", animal: "sloth", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-sloth-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m.webp") },
  { id: "snail-f", animal: "snail", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-snail-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f.webp") },
  { id: "squirrel-f", animal: "squirrel", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-squirrel-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f.webp") },
  { id: "tiger-m", animal: "tiger", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-tiger-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m.webp") },
  { id: "toucan-f", animal: "toucan", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-toucan-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f.webp") },
  { id: "turtle-m", animal: "turtle", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-turtle-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m.webp") },
  { id: "wolf-m", animal: "wolf", gender: "m", style: "90s", source: require("@/assets/avatars/avatar-wolf-m.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m.webp") },
  { id: "zebra-f", animal: "zebra", gender: "f", style: "90s", source: require("@/assets/avatars/avatar-zebra-f.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f.webp") },
  { id: "bat-m-20s", animal: "bat", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-bat-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m-20s.webp") },
  { id: "bear-m-20s", animal: "bear", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-bear-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m-20s.webp") },
  { id: "bee-f-20s", animal: "bee", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-bee-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f-20s.webp") },
  { id: "bull-m-20s", animal: "bull", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-bull-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m-20s.webp") },
  { id: "butterfly-f-20s", animal: "butterfly", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-butterfly-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f-20s.webp") },
  { id: "cat-f-20s", animal: "cat", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-cat-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f-20s.webp") },
  { id: "chameleon-m-20s", animal: "chameleon", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-chameleon-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m-20s.webp") },
  { id: "crab-m-20s", animal: "crab", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-crab-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m-20s.webp") },
  { id: "crocodile-m-20s", animal: "crocodile", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-crocodile-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m-20s.webp") },
  { id: "deer-m-20s", animal: "deer", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-deer-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m-20s.webp") },
  { id: "dog-m-20s", animal: "dog", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-dog-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m-20s.webp") },
  { id: "dolphin-f-20s", animal: "dolphin", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-dolphin-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f-20s.webp") },
  { id: "dragon-m-20s", animal: "dragon", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-dragon-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m-20s.webp") },
  { id: "eagle-m-20s", animal: "eagle", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-eagle-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m-20s.webp") },
  { id: "elephant-m-20s", animal: "elephant", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-elephant-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m-20s.webp") },
  { id: "flamingo-f-20s", animal: "flamingo", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-flamingo-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f-20s.webp") },
  { id: "fox-f-20s", animal: "fox", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-fox-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f-20s.webp") },
  { id: "frog-f-20s", animal: "frog", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-frog-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f-20s.webp") },
  { id: "giraffe-f-20s", animal: "giraffe", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-giraffe-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f-20s.webp") },
  { id: "goat-m-20s", animal: "goat", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-goat-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m-20s.webp") },
  { id: "gorilla-m-20s", animal: "gorilla", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-gorilla-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m-20s.webp") },
  { id: "hamster-f-20s", animal: "hamster", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-hamster-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f-20s.webp") },
  { id: "hedgehog-f-20s", animal: "hedgehog", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-hedgehog-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f-20s.webp") },
  { id: "hippo-m-20s", animal: "hippo", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-hippo-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m-20s.webp") },
  { id: "horse-m-20s", animal: "horse", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-horse-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m-20s.webp") },
  { id: "jellyfish-f-20s", animal: "jellyfish", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-jellyfish-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f-20s.webp") },
  { id: "kangaroo-m-20s", animal: "kangaroo", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-kangaroo-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m-20s.webp") },
  { id: "koala-f-20s", animal: "koala", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-koala-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f-20s.webp") },
  { id: "lion-m-20s", animal: "lion", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-lion-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m-20s.webp") },
  { id: "llama-f-20s", animal: "llama", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-llama-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f-20s.webp") },
  { id: "monkey-m-20s", animal: "monkey", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-monkey-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m-20s.webp") },
  { id: "octopus-f-20s", animal: "octopus", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-octopus-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f-20s.webp") },
  { id: "owl-m-20s", animal: "owl", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-owl-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m-20s.webp") },
  { id: "panda-f-20s", animal: "panda", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-panda-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f-20s.webp") },
  { id: "parrot-f-20s", animal: "parrot", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-parrot-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f-20s.webp") },
  { id: "penguin-f-20s", animal: "penguin", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-penguin-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f-20s.webp") },
  { id: "pig-f-20s", animal: "pig", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-pig-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f-20s.webp") },
  { id: "rabbit-f-20s", animal: "rabbit", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-rabbit-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f-20s.webp") },
  { id: "raccoon-f-20s", animal: "raccoon", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-raccoon-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f-20s.webp") },
  { id: "rhino-m-20s", animal: "rhino", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-rhino-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m-20s.webp") },
  { id: "seahorse-f-20s", animal: "seahorse", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-seahorse-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f-20s.webp") },
  { id: "shark-m-20s", animal: "shark", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-shark-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m-20s.webp") },
  { id: "sloth-m-20s", animal: "sloth", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-sloth-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m-20s.webp") },
  { id: "snail-f-20s", animal: "snail", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-snail-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f-20s.webp") },
  { id: "squirrel-f-20s", animal: "squirrel", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-squirrel-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f-20s.webp") },
  { id: "tiger-m-20s", animal: "tiger", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-tiger-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m-20s.webp") },
  { id: "toucan-f-20s", animal: "toucan", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-toucan-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f-20s.webp") },
  { id: "turtle-m-20s", animal: "turtle", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-turtle-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m-20s.webp") },
  { id: "wolf-m-20s", animal: "wolf", gender: "m", style: "1920s", source: require("@/assets/avatars/avatar-wolf-m-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m-20s.webp") },
  { id: "zebra-f-20s", animal: "zebra", gender: "f", style: "1920s", source: require("@/assets/avatars/avatar-zebra-f-20s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f-20s.webp") },
  { id: "bat-m-50s", animal: "bat", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-bat-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m-50s.webp") },
  { id: "bear-m-50s", animal: "bear", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-bear-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m-50s.webp") },
  { id: "bee-f-50s", animal: "bee", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-bee-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f-50s.webp") },
  { id: "bull-m-50s", animal: "bull", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-bull-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m-50s.webp") },
  { id: "butterfly-f-50s", animal: "butterfly", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-butterfly-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f-50s.webp") },
  { id: "cat-f-50s", animal: "cat", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-cat-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f-50s.webp") },
  { id: "chameleon-m-50s", animal: "chameleon", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-chameleon-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m-50s.webp") },
  { id: "crab-m-50s", animal: "crab", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-crab-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m-50s.webp") },
  { id: "crocodile-m-50s", animal: "crocodile", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-crocodile-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m-50s.webp") },
  { id: "deer-m-50s", animal: "deer", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-deer-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m-50s.webp") },
  { id: "dog-m-50s", animal: "dog", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-dog-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m-50s.webp") },
  { id: "dolphin-f-50s", animal: "dolphin", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-dolphin-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f-50s.webp") },
  { id: "dragon-m-50s", animal: "dragon", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-dragon-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m-50s.webp") },
  { id: "eagle-m-50s", animal: "eagle", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-eagle-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m-50s.webp") },
  { id: "elephant-m-50s", animal: "elephant", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-elephant-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m-50s.webp") },
  { id: "flamingo-f-50s", animal: "flamingo", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-flamingo-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f-50s.webp") },
  { id: "fox-f-50s", animal: "fox", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-fox-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f-50s.webp") },
  { id: "frog-f-50s", animal: "frog", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-frog-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f-50s.webp") },
  { id: "giraffe-f-50s", animal: "giraffe", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-giraffe-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f-50s.webp") },
  { id: "goat-m-50s", animal: "goat", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-goat-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m-50s.webp") },
  { id: "gorilla-m-50s", animal: "gorilla", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-gorilla-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m-50s.webp") },
  { id: "hamster-f-50s", animal: "hamster", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-hamster-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f-50s.webp") },
  { id: "hedgehog-f-50s", animal: "hedgehog", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-hedgehog-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f-50s.webp") },
  { id: "hippo-m-50s", animal: "hippo", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-hippo-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m-50s.webp") },
  { id: "horse-m-50s", animal: "horse", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-horse-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m-50s.webp") },
  { id: "jellyfish-f-50s", animal: "jellyfish", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-jellyfish-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f-50s.webp") },
  { id: "kangaroo-m-50s", animal: "kangaroo", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-kangaroo-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m-50s.webp") },
  { id: "koala-f-50s", animal: "koala", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-koala-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f-50s.webp") },
  { id: "lion-m-50s", animal: "lion", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-lion-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m-50s.webp") },
  { id: "llama-f-50s", animal: "llama", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-llama-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f-50s.webp") },
  { id: "monkey-m-50s", animal: "monkey", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-monkey-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m-50s.webp") },
  { id: "octopus-f-50s", animal: "octopus", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-octopus-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f-50s.webp") },
  { id: "owl-m-50s", animal: "owl", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-owl-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m-50s.webp") },
  { id: "panda-f-50s", animal: "panda", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-panda-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f-50s.webp") },
  { id: "parrot-f-50s", animal: "parrot", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-parrot-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f-50s.webp") },
  { id: "penguin-f-50s", animal: "penguin", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-penguin-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f-50s.webp") },
  { id: "pig-f-50s", animal: "pig", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-pig-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f-50s.webp") },
  { id: "rabbit-f-50s", animal: "rabbit", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-rabbit-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f-50s.webp") },
  { id: "raccoon-f-50s", animal: "raccoon", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-raccoon-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f-50s.webp") },
  { id: "rhino-m-50s", animal: "rhino", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-rhino-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m-50s.webp") },
  { id: "seahorse-f-50s", animal: "seahorse", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-seahorse-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f-50s.webp") },
  { id: "shark-m-50s", animal: "shark", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-shark-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m-50s.webp") },
  { id: "sloth-m-50s", animal: "sloth", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-sloth-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m-50s.webp") },
  { id: "snail-f-50s", animal: "snail", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-snail-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f-50s.webp") },
  { id: "squirrel-f-50s", animal: "squirrel", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-squirrel-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f-50s.webp") },
  { id: "tiger-m-50s", animal: "tiger", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-tiger-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m-50s.webp") },
  { id: "toucan-f-50s", animal: "toucan", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-toucan-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f-50s.webp") },
  { id: "turtle-m-50s", animal: "turtle", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-turtle-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m-50s.webp") },
  { id: "wolf-m-50s", animal: "wolf", gender: "m", style: "1950s", source: require("@/assets/avatars/avatar-wolf-m-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m-50s.webp") },
  { id: "zebra-f-50s", animal: "zebra", gender: "f", style: "1950s", source: require("@/assets/avatars/avatar-zebra-f-50s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f-50s.webp") },
  { id: "bat-m-70s", animal: "bat", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-bat-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m-70s.webp") },
  { id: "bear-m-70s", animal: "bear", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-bear-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m-70s.webp") },
  { id: "bee-f-70s", animal: "bee", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-bee-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f-70s.webp") },
  { id: "bull-m-70s", animal: "bull", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-bull-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m-70s.webp") },
  { id: "butterfly-f-70s", animal: "butterfly", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-butterfly-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f-70s.webp") },
  { id: "cat-f-70s", animal: "cat", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-cat-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f-70s.webp") },
  { id: "chameleon-m-70s", animal: "chameleon", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-chameleon-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m-70s.webp") },
  { id: "crab-m-70s", animal: "crab", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-crab-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m-70s.webp") },
  { id: "crocodile-m-70s", animal: "crocodile", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-crocodile-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m-70s.webp") },
  { id: "deer-m-70s", animal: "deer", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-deer-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m-70s.webp") },
  { id: "dog-m-70s", animal: "dog", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-dog-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m-70s.webp") },
  { id: "dolphin-f-70s", animal: "dolphin", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-dolphin-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f-70s.webp") },
  { id: "dragon-m-70s", animal: "dragon", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-dragon-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m-70s.webp") },
  { id: "eagle-m-70s", animal: "eagle", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-eagle-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m-70s.webp") },
  { id: "elephant-m-70s", animal: "elephant", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-elephant-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m-70s.webp") },
  { id: "flamingo-f-70s", animal: "flamingo", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-flamingo-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f-70s.webp") },
  { id: "fox-f-70s", animal: "fox", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-fox-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f-70s.webp") },
  { id: "frog-f-70s", animal: "frog", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-frog-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f-70s.webp") },
  { id: "giraffe-f-70s", animal: "giraffe", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-giraffe-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f-70s.webp") },
  { id: "goat-m-70s", animal: "goat", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-goat-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m-70s.webp") },
  { id: "gorilla-m-70s", animal: "gorilla", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-gorilla-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m-70s.webp") },
  { id: "hamster-f-70s", animal: "hamster", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-hamster-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f-70s.webp") },
  { id: "hedgehog-f-70s", animal: "hedgehog", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-hedgehog-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f-70s.webp") },
  { id: "hippo-m-70s", animal: "hippo", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-hippo-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m-70s.webp") },
  { id: "horse-m-70s", animal: "horse", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-horse-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m-70s.webp") },
  { id: "jellyfish-f-70s", animal: "jellyfish", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-jellyfish-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f-70s.webp") },
  { id: "kangaroo-m-70s", animal: "kangaroo", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-kangaroo-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m-70s.webp") },
  { id: "koala-f-70s", animal: "koala", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-koala-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f-70s.webp") },
  { id: "lion-m-70s", animal: "lion", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-lion-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m-70s.webp") },
  { id: "llama-f-70s", animal: "llama", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-llama-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f-70s.webp") },
  { id: "monkey-m-70s", animal: "monkey", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-monkey-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m-70s.webp") },
  { id: "octopus-f-70s", animal: "octopus", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-octopus-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f-70s.webp") },
  { id: "owl-m-70s", animal: "owl", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-owl-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m-70s.webp") },
  { id: "panda-f-70s", animal: "panda", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-panda-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f-70s.webp") },
  { id: "parrot-f-70s", animal: "parrot", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-parrot-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f-70s.webp") },
  { id: "penguin-f-70s", animal: "penguin", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-penguin-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f-70s.webp") },
  { id: "pig-f-70s", animal: "pig", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-pig-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f-70s.webp") },
  { id: "rabbit-f-70s", animal: "rabbit", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-rabbit-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f-70s.webp") },
  { id: "raccoon-f-70s", animal: "raccoon", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-raccoon-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f-70s.webp") },
  { id: "rhino-m-70s", animal: "rhino", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-rhino-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m-70s.webp") },
  { id: "seahorse-f-70s", animal: "seahorse", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-seahorse-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f-70s.webp") },
  { id: "shark-m-70s", animal: "shark", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-shark-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m-70s.webp") },
  { id: "sloth-m-70s", animal: "sloth", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-sloth-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m-70s.webp") },
  { id: "snail-f-70s", animal: "snail", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-snail-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f-70s.webp") },
  { id: "squirrel-f-70s", animal: "squirrel", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-squirrel-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f-70s.webp") },
  { id: "tiger-m-70s", animal: "tiger", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-tiger-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m-70s.webp") },
  { id: "toucan-f-70s", animal: "toucan", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-toucan-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f-70s.webp") },
  { id: "turtle-m-70s", animal: "turtle", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-turtle-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m-70s.webp") },
  { id: "wolf-m-70s", animal: "wolf", gender: "m", style: "1970s", source: require("@/assets/avatars/avatar-wolf-m-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m-70s.webp") },
  { id: "zebra-f-70s", animal: "zebra", gender: "f", style: "1970s", source: require("@/assets/avatars/avatar-zebra-f-70s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f-70s.webp") },
  { id: "bat-m-80s", animal: "bat", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-bat-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m-80s.webp") },
  { id: "bear-m-80s", animal: "bear", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-bear-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m-80s.webp") },
  { id: "bee-f-80s", animal: "bee", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-bee-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f-80s.webp") },
  { id: "bull-m-80s", animal: "bull", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-bull-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m-80s.webp") },
  { id: "butterfly-f-80s", animal: "butterfly", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-butterfly-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f-80s.webp") },
  { id: "cat-f-80s", animal: "cat", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-cat-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f-80s.webp") },
  { id: "chameleon-m-80s", animal: "chameleon", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-chameleon-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m-80s.webp") },
  { id: "crab-m-80s", animal: "crab", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-crab-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m-80s.webp") },
  { id: "crocodile-m-80s", animal: "crocodile", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-crocodile-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m-80s.webp") },
  { id: "deer-m-80s", animal: "deer", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-deer-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m-80s.webp") },
  { id: "dog-m-80s", animal: "dog", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-dog-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m-80s.webp") },
  { id: "dolphin-f-80s", animal: "dolphin", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-dolphin-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f-80s.webp") },
  { id: "dragon-m-80s", animal: "dragon", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-dragon-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m-80s.webp") },
  { id: "eagle-m-80s", animal: "eagle", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-eagle-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m-80s.webp") },
  { id: "elephant-m-80s", animal: "elephant", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-elephant-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m-80s.webp") },
  { id: "flamingo-f-80s", animal: "flamingo", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-flamingo-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f-80s.webp") },
  { id: "fox-f-80s", animal: "fox", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-fox-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f-80s.webp") },
  { id: "frog-f-80s", animal: "frog", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-frog-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f-80s.webp") },
  { id: "giraffe-f-80s", animal: "giraffe", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-giraffe-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f-80s.webp") },
  { id: "goat-m-80s", animal: "goat", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-goat-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m-80s.webp") },
  { id: "gorilla-m-80s", animal: "gorilla", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-gorilla-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m-80s.webp") },
  { id: "hamster-f-80s", animal: "hamster", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-hamster-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f-80s.webp") },
  { id: "hedgehog-f-80s", animal: "hedgehog", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-hedgehog-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f-80s.webp") },
  { id: "hippo-m-80s", animal: "hippo", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-hippo-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m-80s.webp") },
  { id: "horse-m-80s", animal: "horse", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-horse-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m-80s.webp") },
  { id: "jellyfish-f-80s", animal: "jellyfish", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-jellyfish-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f-80s.webp") },
  { id: "kangaroo-m-80s", animal: "kangaroo", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-kangaroo-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m-80s.webp") },
  { id: "koala-f-80s", animal: "koala", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-koala-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f-80s.webp") },
  { id: "lion-m-80s", animal: "lion", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-lion-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m-80s.webp") },
  { id: "llama-f-80s", animal: "llama", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-llama-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f-80s.webp") },
  { id: "monkey-m-80s", animal: "monkey", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-monkey-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m-80s.webp") },
  { id: "octopus-f-80s", animal: "octopus", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-octopus-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f-80s.webp") },
  { id: "owl-m-80s", animal: "owl", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-owl-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m-80s.webp") },
  { id: "panda-f-80s", animal: "panda", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-panda-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f-80s.webp") },
  { id: "parrot-f-80s", animal: "parrot", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-parrot-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f-80s.webp") },
  { id: "penguin-f-80s", animal: "penguin", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-penguin-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f-80s.webp") },
  { id: "pig-f-80s", animal: "pig", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-pig-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f-80s.webp") },
  { id: "rabbit-f-80s", animal: "rabbit", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-rabbit-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f-80s.webp") },
  { id: "raccoon-f-80s", animal: "raccoon", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-raccoon-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f-80s.webp") },
  { id: "rhino-m-80s", animal: "rhino", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-rhino-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m-80s.webp") },
  { id: "seahorse-f-80s", animal: "seahorse", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-seahorse-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f-80s.webp") },
  { id: "shark-m-80s", animal: "shark", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-shark-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m-80s.webp") },
  { id: "sloth-m-80s", animal: "sloth", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-sloth-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m-80s.webp") },
  { id: "snail-f-80s", animal: "snail", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-snail-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f-80s.webp") },
  { id: "squirrel-f-80s", animal: "squirrel", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-squirrel-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f-80s.webp") },
  { id: "tiger-m-80s", animal: "tiger", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-tiger-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m-80s.webp") },
  { id: "toucan-f-80s", animal: "toucan", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-toucan-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f-80s.webp") },
  { id: "turtle-m-80s", animal: "turtle", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-turtle-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m-80s.webp") },
  { id: "wolf-m-80s", animal: "wolf", gender: "m", style: "1980s", source: require("@/assets/avatars/avatar-wolf-m-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m-80s.webp") },
  { id: "zebra-f-80s", animal: "zebra", gender: "f", style: "1980s", source: require("@/assets/avatars/avatar-zebra-f-80s.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f-80s.webp") },
  { id: "bat-m-y2k", animal: "bat", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-bat-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bat-m-y2k.webp") },
  { id: "bear-m-y2k", animal: "bear", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-bear-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bear-m-y2k.webp") },
  { id: "bee-f-y2k", animal: "bee", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-bee-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bee-f-y2k.webp") },
  { id: "bull-m-y2k", animal: "bull", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-bull-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-bull-m-y2k.webp") },
  { id: "butterfly-f-y2k", animal: "butterfly", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-butterfly-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-butterfly-f-y2k.webp") },
  { id: "cat-f-y2k", animal: "cat", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-cat-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-cat-f-y2k.webp") },
  { id: "chameleon-m-y2k", animal: "chameleon", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-chameleon-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-chameleon-m-y2k.webp") },
  { id: "crab-m-y2k", animal: "crab", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-crab-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crab-m-y2k.webp") },
  { id: "crocodile-m-y2k", animal: "crocodile", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-crocodile-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-crocodile-m-y2k.webp") },
  { id: "deer-m-y2k", animal: "deer", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-deer-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-deer-m-y2k.webp") },
  { id: "dog-m-y2k", animal: "dog", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-dog-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dog-m-y2k.webp") },
  { id: "dolphin-f-y2k", animal: "dolphin", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-dolphin-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dolphin-f-y2k.webp") },
  { id: "dragon-m-y2k", animal: "dragon", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-dragon-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-dragon-m-y2k.webp") },
  { id: "eagle-m-y2k", animal: "eagle", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-eagle-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-eagle-m-y2k.webp") },
  { id: "elephant-m-y2k", animal: "elephant", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-elephant-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-elephant-m-y2k.webp") },
  { id: "flamingo-f-y2k", animal: "flamingo", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-flamingo-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-flamingo-f-y2k.webp") },
  { id: "fox-f-y2k", animal: "fox", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-fox-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-fox-f-y2k.webp") },
  { id: "frog-f-y2k", animal: "frog", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-frog-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-frog-f-y2k.webp") },
  { id: "giraffe-f-y2k", animal: "giraffe", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-giraffe-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-giraffe-f-y2k.webp") },
  { id: "goat-m-y2k", animal: "goat", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-goat-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-goat-m-y2k.webp") },
  { id: "gorilla-m-y2k", animal: "gorilla", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-gorilla-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-gorilla-m-y2k.webp") },
  { id: "hamster-f-y2k", animal: "hamster", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-hamster-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hamster-f-y2k.webp") },
  { id: "hedgehog-f-y2k", animal: "hedgehog", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-hedgehog-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hedgehog-f-y2k.webp") },
  { id: "hippo-m-y2k", animal: "hippo", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-hippo-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-hippo-m-y2k.webp") },
  { id: "horse-m-y2k", animal: "horse", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-horse-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-horse-m-y2k.webp") },
  { id: "jellyfish-f-y2k", animal: "jellyfish", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-jellyfish-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-jellyfish-f-y2k.webp") },
  { id: "kangaroo-m-y2k", animal: "kangaroo", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-kangaroo-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-kangaroo-m-y2k.webp") },
  { id: "koala-f-y2k", animal: "koala", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-koala-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-koala-f-y2k.webp") },
  { id: "lion-m-y2k", animal: "lion", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-lion-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-lion-m-y2k.webp") },
  { id: "llama-f-y2k", animal: "llama", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-llama-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-llama-f-y2k.webp") },
  { id: "monkey-m-y2k", animal: "monkey", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-monkey-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-monkey-m-y2k.webp") },
  { id: "octopus-f-y2k", animal: "octopus", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-octopus-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-octopus-f-y2k.webp") },
  { id: "owl-m-y2k", animal: "owl", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-owl-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-owl-m-y2k.webp") },
  { id: "panda-f-y2k", animal: "panda", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-panda-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-panda-f-y2k.webp") },
  { id: "parrot-f-y2k", animal: "parrot", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-parrot-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-parrot-f-y2k.webp") },
  { id: "penguin-f-y2k", animal: "penguin", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-penguin-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-penguin-f-y2k.webp") },
  { id: "pig-f-y2k", animal: "pig", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-pig-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-pig-f-y2k.webp") },
  { id: "rabbit-f-y2k", animal: "rabbit", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-rabbit-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rabbit-f-y2k.webp") },
  { id: "raccoon-f-y2k", animal: "raccoon", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-raccoon-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-raccoon-f-y2k.webp") },
  { id: "rhino-m-y2k", animal: "rhino", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-rhino-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-rhino-m-y2k.webp") },
  { id: "seahorse-f-y2k", animal: "seahorse", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-seahorse-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-seahorse-f-y2k.webp") },
  { id: "shark-m-y2k", animal: "shark", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-shark-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-shark-m-y2k.webp") },
  { id: "sloth-m-y2k", animal: "sloth", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-sloth-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-sloth-m-y2k.webp") },
  { id: "snail-f-y2k", animal: "snail", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-snail-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-snail-f-y2k.webp") },
  { id: "squirrel-f-y2k", animal: "squirrel", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-squirrel-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-squirrel-f-y2k.webp") },
  { id: "tiger-m-y2k", animal: "tiger", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-tiger-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-tiger-m-y2k.webp") },
  { id: "toucan-f-y2k", animal: "toucan", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-toucan-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-toucan-f-y2k.webp") },
  { id: "turtle-m-y2k", animal: "turtle", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-turtle-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-turtle-m-y2k.webp") },
  { id: "wolf-m-y2k", animal: "wolf", gender: "m", style: "Y2K", source: require("@/assets/avatars/avatar-wolf-m-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-wolf-m-y2k.webp") },
  { id: "zebra-f-y2k", animal: "zebra", gender: "f", style: "Y2K", source: require("@/assets/avatars/avatar-zebra-f-y2k.webp"), thumbnail: require("@/assets/avatars/thumbs/avatar-zebra-f-y2k.webp") },
];

export const SHINY_AVATARS = {
  "bull-shiny": require("@/assets/avatars/shiny/avatar-bull-shiny.webp"),
  "camel-shiny": require("@/assets/avatars/shiny/avatar-camel-shiny.webp"),
  "dove-shiny": require("@/assets/avatars/shiny/avatar-dove-shiny.webp"),
  "dragon-shiny": require("@/assets/avatars/shiny/avatar-dragon-shiny.webp"),
  "eagle-shiny": require("@/assets/avatars/shiny/avatar-eagle-shiny.webp"),
  "fox-shiny": require("@/assets/avatars/shiny/avatar-fox-shiny.webp"),
  "kangaroo-shiny": require("@/assets/avatars/shiny/avatar-kangaroo-shiny.webp"),
  "lion-shiny": require("@/assets/avatars/shiny/avatar-lion-shiny.webp"),
  "owl-shiny": require("@/assets/avatars/shiny/avatar-owl-shiny.webp"),
  "parrot-shiny": require("@/assets/avatars/shiny/avatar-parrot-shiny.webp"),
  "prayercircle-shiny": require("@/assets/avatars/shiny/avatar-prayercircle-shiny.webp"),
  "tiger-shiny": require("@/assets/avatars/shiny/avatar-tiger-shiny.webp"),
  "upper-room-shiny": require("@/assets/avatars/shiny/avatar-upper-room-shiny.webp"),
  "carmels-fire-shiny": require("@/assets/avatars/shiny/avatar-carmels-fire-shiny.webp"),
  "nehemiahs-watch-shiny": require("@/assets/avatars/shiny/avatar-nehemiahs-watch-shiny.webp"),
  "midnight-hymn-shiny": require("@/assets/avatars/shiny/avatar-midnight-hymn-shiny.webp"),
  "wilderness-prayer-shiny": require("@/assets/avatars/shiny/avatar-wilderness-prayer-shiny.webp"),
  "lords-prayer-shiny": require("@/assets/avatars/shiny/avatar-lords-prayer-shiny.webp"),
  "cloud-witnesses-shiny": require("@/assets/avatars/shiny/avatar-cloud-witnesses-shiny.webp"),
  "esthers-courage-shiny": require("@/assets/avatars/shiny/avatar-esthers-courage-shiny.webp"),
  "daniels-resolve-shiny": require("@/assets/avatars/shiny/avatar-daniels-resolve-shiny.webp"),
  "ninevehs-mercy-shiny": require("@/assets/avatars/shiny/avatar-ninevehs-mercy-shiny.webp"),
  "elijahs-strength-shiny": require("@/assets/avatars/shiny/avatar-elijahs-strength-shiny.webp"),
  "sinais-glory-shiny": require("@/assets/avatars/shiny/avatar-sinais-glory-shiny.webp"),
  "paul-apostle-shiny": require("@/assets/avatars/shiny/avatar-paul-apostle-shiny.webp"),
  "daniel-shiny": require("@/assets/avatars/shiny/avatar-daniel-shiny.webp"),
  "joseph-shiny": require("@/assets/avatars/shiny/avatar-joseph-shiny.webp"),
  "abraham-shiny": require("@/assets/avatars/shiny/avatar-abraham-shiny.webp"),
  "moses-shiny": require("@/assets/avatars/shiny/avatar-moses-shiny.webp"),
  "david-shiny": require("@/assets/avatars/shiny/avatar-david-shiny.webp"),
  "esther-shiny": require("@/assets/avatars/shiny/avatar-esther-shiny.webp"),
  "fish-loaves-shiny": require("@/assets/avatars/shiny/avatar-fish-loaves-shiny.webp"),
  "donkey-shiny": require("@/assets/avatars/shiny/avatar-donkey-shiny.webp"),
  "sheep-shiny": require("@/assets/avatars/shiny/avatar-sheep-shiny.webp"),
  "lion-judah-shiny": require("@/assets/avatars/shiny/avatar-lion-judah-shiny.webp"),
  "lamb-god-shiny": require("@/assets/avatars/shiny/avatar-lamb-god-shiny.webp"),
  "eagle-wings-shiny": require("@/assets/avatars/shiny/avatar-eagle-wings-shiny.webp"),
  "raven-provision-shiny": require("@/assets/avatars/shiny/avatar-raven-provision-shiny.webp"),
} as const;

export const SHINY_AVATAR_THUMBNAILS = {
  "bull-shiny": require("@/assets/avatars/thumbs/avatar-bull-shiny.webp"),
  "camel-shiny": require("@/assets/avatars/thumbs/avatar-camel-shiny.webp"),
  "dove-shiny": require("@/assets/avatars/thumbs/avatar-dove-shiny.webp"),
  "dragon-shiny": require("@/assets/avatars/thumbs/avatar-dragon-shiny.webp"),
  "eagle-shiny": require("@/assets/avatars/thumbs/avatar-eagle-shiny.webp"),
  "fox-shiny": require("@/assets/avatars/thumbs/avatar-fox-shiny.webp"),
  "kangaroo-shiny": require("@/assets/avatars/thumbs/avatar-kangaroo-shiny.webp"),
  "lion-shiny": require("@/assets/avatars/thumbs/avatar-lion-shiny.webp"),
  "owl-shiny": require("@/assets/avatars/thumbs/avatar-owl-shiny.webp"),
  "parrot-shiny": require("@/assets/avatars/thumbs/avatar-parrot-shiny.webp"),
  "prayercircle-shiny": require("@/assets/avatars/thumbs/avatar-prayercircle-shiny.webp"),
  "tiger-shiny": require("@/assets/avatars/thumbs/avatar-tiger-shiny.webp"),
  "upper-room-shiny": require("@/assets/avatars/shiny/avatar-upper-room-shiny.webp"),
  "carmels-fire-shiny": require("@/assets/avatars/shiny/avatar-carmels-fire-shiny.webp"),
  "nehemiahs-watch-shiny": require("@/assets/avatars/shiny/avatar-nehemiahs-watch-shiny.webp"),
  "midnight-hymn-shiny": require("@/assets/avatars/shiny/avatar-midnight-hymn-shiny.webp"),
  "wilderness-prayer-shiny": require("@/assets/avatars/shiny/avatar-wilderness-prayer-shiny.webp"),
  "lords-prayer-shiny": require("@/assets/avatars/shiny/avatar-lords-prayer-shiny.webp"),
  "cloud-witnesses-shiny": require("@/assets/avatars/shiny/avatar-cloud-witnesses-shiny.webp"),
  "esthers-courage-shiny": require("@/assets/avatars/shiny/avatar-esthers-courage-shiny.webp"),
  "daniels-resolve-shiny": require("@/assets/avatars/shiny/avatar-daniels-resolve-shiny.webp"),
  "ninevehs-mercy-shiny": require("@/assets/avatars/shiny/avatar-ninevehs-mercy-shiny.webp"),
  "elijahs-strength-shiny": require("@/assets/avatars/shiny/avatar-elijahs-strength-shiny.webp"),
  "sinais-glory-shiny": require("@/assets/avatars/shiny/avatar-sinais-glory-shiny.webp"),
  "paul-apostle-shiny": require("@/assets/avatars/shiny/avatar-paul-apostle-shiny.webp"),
  "daniel-shiny": require("@/assets/avatars/shiny/avatar-daniel-shiny.webp"),
  "joseph-shiny": require("@/assets/avatars/shiny/avatar-joseph-shiny.webp"),
  "abraham-shiny": require("@/assets/avatars/shiny/avatar-abraham-shiny.webp"),
  "moses-shiny": require("@/assets/avatars/shiny/avatar-moses-shiny.webp"),
  "david-shiny": require("@/assets/avatars/shiny/avatar-david-shiny.webp"),
  "esther-shiny": require("@/assets/avatars/shiny/avatar-esther-shiny.webp"),
  "fish-loaves-shiny": require("@/assets/avatars/shiny/avatar-fish-loaves-shiny.webp"),
  "donkey-shiny": require("@/assets/avatars/shiny/avatar-donkey-shiny.webp"),
  "sheep-shiny": require("@/assets/avatars/shiny/avatar-sheep-shiny.webp"),
  "lion-judah-shiny": require("@/assets/avatars/shiny/avatar-lion-judah-shiny.webp"),
  "lamb-god-shiny": require("@/assets/avatars/shiny/avatar-lamb-god-shiny.webp"),
  "eagle-wings-shiny": require("@/assets/avatars/shiny/avatar-eagle-wings-shiny.webp"),
  "raven-provision-shiny": require("@/assets/avatars/shiny/avatar-raven-provision-shiny.webp"),
} as const;

export const HERO_AVATARS = {
  "david-hero": require("@/assets/avatars/heroes/avatar-david-hero.webp"),
  "moses-hero": require("@/assets/avatars/heroes/avatar-moses-hero.webp"),
  "paul-hero": require("@/assets/avatars/heroes/avatar-paul-hero.webp"),
  "peter-hero": require("@/assets/avatars/heroes/avatar-peter-hero.webp"),
  "esther-hero": require("@/assets/avatars/heroes/avatar-esther-hero.webp"),
  "daniel-hero": require("@/assets/avatars/heroes/avatar-daniel-hero.webp"),
  "spurgeon-hero": require("@/assets/avatars/heroes/avatar-spurgeon-hero.webp"),
  "moody-hero": require("@/assets/avatars/heroes/avatar-moody-hero.webp"),
  "noah-hero": require("@/assets/avatars/heroes/avatar-noah-hero.webp"),
  "elijah-hero": require("@/assets/avatars/heroes/avatar-elijah-hero.webp"),
  "samuel-hero": require("@/assets/avatars/heroes/avatar-samuel-hero.webp"),
  "ruth-hero": require("@/assets/avatars/heroes/avatar-ruth-hero.webp"),
  "johnbaptist-hero": require("@/assets/avatars/heroes/avatar-johnbaptist-hero.webp"),
  "mary-hero": require("@/assets/avatars/heroes/avatar-mary-hero.webp"),
  "luther-hero": require("@/assets/avatars/heroes/avatar-luther-hero.webp"),
  "corrie-hero": require("@/assets/avatars/heroes/avatar-corrie-hero.webp"),
} as const;

export const SHINY_HERO_AVATARS = {
  "jesus-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-jesus-shiny-hero.webp"),
  "abraham-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-abraham-shiny-hero.webp"),
  "joseph-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-joseph-shiny-hero.webp"),
  "david-shiny-hero": require("@/assets/avatars/shiny-heroes/avatar-david-shiny-hero.webp"),
} as const;

export type ShinyHeroAvatarId = keyof typeof SHINY_HERO_AVATARS;

export type HeroAvatarId = keyof typeof HERO_AVATARS;

export const HERO_ACHIEVEMENTS = [
  { id: "evo-david-3", name: "David", hint: "Reach a 30-day prayer streak", avatarId: "david-hero", title: "David the King" },
  { id: "fast-40", name: "Moses", hint: "Complete a 40-day fast", avatarId: "moses-hero", title: "Moses" },
  { id: "evo-paul-3", name: "Paul", hint: "Reach a 50-day prayer streak", avatarId: "paul-hero", title: "Paul the Apostle" },
  { id: "evo-peter-3", name: "Peter", hint: "Complete a 30-day fast", avatarId: "peter-hero", title: "Peter the Restored" },
  { id: "fast-5", name: "Esther", hint: "Complete a 5-day fast", avatarId: "esther-hero", title: "Esther" },
  { id: "fast-10", name: "Daniel", hint: "Complete a 10-day fast", avatarId: "daniel-hero", title: "Daniel" },
  { id: "fast-100", name: "Spurgeon", hint: "Complete a 100-day fast", avatarId: "spurgeon-hero", title: "Charles Spurgeon" },
  { id: "streak-100", name: "Moody", hint: "Reach a 100-day prayer streak", avatarId: "moody-hero", title: "D.L. Moody" },
  { id: "fast-7", name: "Noah", hint: "Complete a 7-day fast", avatarId: "noah-hero", title: "Noah the Ark Builder" },
  { id: "fast-21", name: "Elijah", hint: "Complete a 21-day fast", avatarId: "elijah-hero", title: "Elijah the Prophet" },
  { id: "streak-15", name: "Samuel", hint: "Reach a 15-day prayer streak", avatarId: "samuel-hero", title: "Samuel the Prophet" },
  { id: "streak-7", name: "Ruth", hint: "Reach a 7-day prayer streak", avatarId: "ruth-hero", title: "Ruth the Loyal" },
  { id: "fast-30", name: "John the Baptist", hint: "Complete a 30-day fast", avatarId: "johnbaptist-hero", title: "John the Baptist" },
  { id: "streak-25", name: "Mary", hint: "Reach a 25-day prayer streak", avatarId: "mary-hero", title: "Mary the Mother" },
  { id: "streak-50", name: "Luther", hint: "Reach a 50-day prayer streak", avatarId: "luther-hero", title: "Martin Luther" },
  { id: "fast-60", name: "Corrie", hint: "Complete a 60-day fast", avatarId: "corrie-hero", title: "Corrie ten Boom" },
] as const;

export type ShinyAvatarId = keyof typeof SHINY_AVATARS;

export const SHINY_ACHIEVEMENTS = [
  { id: "first-task", name: "Dawn Lion", hint: "Schedule your first task", avatarId: "lion-shiny", title: "First Task" },
  { id: "full-set", name: "Triune Dragon", hint: "Schedule one task of each type", avatarId: "dragon-shiny", title: "Full Set" },
  { id: "curator", name: "Psalm Parrot", hint: "Save your first album", avatarId: "parrot-shiny", title: "Curator" },
  { id: "streak-5", name: "Upper Room", hint: "Reach a 5-day prayer streak", avatarId: "upper-room-shiny", title: "5-Day Streak" },
  { id: "streak-7", name: "Ember Fox", hint: "Reach a 7-day prayer streak", avatarId: "fox-shiny", title: "7-Day Streak" },
  { id: "streak-10", name: "Carmel's Fire", hint: "Reach a 10-day prayer streak", avatarId: "carmels-fire-shiny", title: "10-Day Streak" },
  { id: "streak-15", name: "Nehemiah's Watch", hint: "Reach a 15-day prayer streak", avatarId: "nehemiahs-watch-shiny", title: "15-Day Streak" },
  { id: "streak-20", name: "Midnight Hymn", hint: "Reach a 20-day prayer streak", avatarId: "midnight-hymn-shiny", title: "20-Day Streak" },
  { id: "streak-21", name: "Covenant Eagle", hint: "Reach a 21-day prayer streak", avatarId: "eagle-shiny", title: "21-Day Streak" },
  { id: "streak-25", name: "Wilderness Prayer", hint: "Reach a 25-day prayer streak", avatarId: "wilderness-prayer-shiny", title: "25-Day Streak" },
  { id: "streak-30", name: "The Lord's Prayer", hint: "Reach a 30-day prayer streak", title: "30-Day Streak" },
  { id: "streak-75", name: "Cloud of Witnesses", hint: "Reach a 75-day prayer streak", avatarId: "cloud-witnesses-shiny", title: "75-Day Streak" },
  { id: "fast-5", name: "Esther's Courage", hint: "Complete a 5-day fast", avatarId: "esthers-courage-shiny", title: "5-Day Fast" },
  { id: "fast-7", name: "Desert Camel", hint: "Complete a 7-day fast", avatarId: "camel-shiny", title: "7-Day Fast" },
  { id: "fast-10", name: "Daniel's Resolve", hint: "Complete a 10-day fast", avatarId: "daniels-resolve-shiny", title: "10-Day Fast" },
  { id: "fast-15", name: "Nineveh's Mercy", hint: "Complete a 15-day fast", avatarId: "ninevehs-mercy-shiny", title: "15-Day Fast" },
  { id: "fast-20", name: "Elijah's Strength", hint: "Complete a 20-day fast", avatarId: "elijahs-strength-shiny", title: "20-Day Fast" },
  { id: "fast-21", name: "Manna Dove", hint: "Complete a 21-day fast", avatarId: "dove-shiny", title: "21-Day Fast" },
  { id: "fast-25", name: "Sinai's Glory", hint: "Complete a 25-day fast", avatarId: "sinais-glory-shiny", title: "25-Day Fast" },
  { id: "fast-30", name: "Temptation's End", hint: "Complete a 30-day fast", title: "30-Day Fast" },
  { id: "fast-60", name: "Intercession", hint: "Complete a 60-day fast", title: "60-Day Fast" },
  { id: "evo-david-1", name: "David the Shepherd", hint: "Reach a 5-day prayer streak", title: "David: Stage 1" },
  { id: "evo-david-2", name: "David the Giant Slayer", hint: "Reach a 15-day prayer streak", title: "David: Stage 2" },
  { id: "evo-david-3", name: "David the King", hint: "Reach a 30-day prayer streak", title: "David: Stage 3" },
  { id: "evo-peter-1", name: "Peter the Fisherman", hint: "Complete a 5-day fast", title: "Peter: Stage 1" },
  { id: "evo-peter-2", name: "Peter the Denier", hint: "Complete a 15-day fast", title: "Peter: Stage 2" },
  { id: "evo-peter-3", name: "Peter the Restored", hint: "Complete a 30-day fast", title: "Peter: Stage 3" },
  { id: "evo-paul-1", name: "Saul the Persecutor", hint: "Reach a 10-day prayer streak", title: "Paul: Stage 1" },
  { id: "evo-paul-2", name: "Saul the Blinded", hint: "Reach a 20-day prayer streak", title: "Paul: Stage 2" },
  { id: "evo-paul-3", name: "Paul the Apostle", hint: "Reach a 50-day prayer streak", title: "Paul: Stage 3" },
  { id: "streak-50", name: "Burning Bush Tiger", hint: "Reach a 50-day prayer streak", avatarId: "tiger-shiny", title: "50-Day Streak" },
  { id: "streak-100", name: "Heavens Owl", hint: "Reach a 100-day prayer streak", avatarId: "owl-shiny", title: "100-Day Streak" },
  { id: "fast-40", name: "Wilderness Kangaroo", hint: "Complete a 40-day fast", avatarId: "kangaroo-shiny", title: "40-Day Fast" },
  { id: "fast-100", name: "Armor of God Bull", hint: "Complete a 100-day fast", avatarId: "bull-shiny", title: "100-Day Fast" },
  { id: "fast-365", name: "Mr. Prayer Circle", hint: "Complete a 365-day fast", avatarId: "prayercircle-shiny", title: "365-Day Fast" },
  { id: "streak-100", name: "Jesus", hint: "Reach a 100-day prayer streak", avatarId: "jesus-shiny-hero", title: "Jesus" },
  { id: "fast-60", name: "Abraham", hint: "Complete a 60-day fast", avatarId: "abraham-shiny-hero", title: "Abraham" },
  { id: "fast-30", name: "Joseph", hint: "Complete a 30-day fast", avatarId: "joseph-shiny-hero", title: "Joseph" },
  { id: "streak-30", name: "David", hint: "Reach a 30-day prayer streak", avatarId: "david-shiny-hero", title: "David" },
  { id: "shiny-manna-dawn", name: "Manna Dove: Dawn", hint: "Complete a 21-day fast", title: "Manna Dawn" },
  { id: "shiny-manna-evening", name: "Manna Dove: Evening", hint: "Complete a 25-day fast", title: "Manna Evening" },
  { id: "shiny-carmel-fire", name: "Elijah: Carmel's Fire", hint: "Reach a 35-day prayer streak", title: "Carmel Fire" },
  { id: "shiny-whirlwind", name: "Elijah: Whirlwind", hint: "Reach a 40-day prayer streak", title: "Whirlwind" },
  { id: "shiny-abraham-starry", name: "Abraham: Starry Sky", hint: "Reach a 45-day prayer streak", avatarId: "abraham-shiny", title: "Starry Sky" },
  { id: "shiny-moses-bush", name: "Moses: Burning Bush", hint: "Complete a 45-day fast", avatarId: "moses-shiny", title: "Burning Bush" },
  { id: "shiny-david-harp", name: "David: Harp", hint: "Reach a 60-day prayer streak", avatarId: "david-shiny", title: "David's Harp" },
  { id: "shiny-esther-crown", name: "Esther: Crown", hint: "Complete a 60-day fast", avatarId: "esther-shiny", title: "Esther's Crown" },
  { id: "shiny-lion-judah", name: "Lion of Judah", hint: "Reach a 75-day prayer streak", avatarId: "lion-judah-shiny", title: "Lion of Judah" },
  { id: "shiny-lamb-god", name: "Lamb of God", hint: "Complete a 75-day fast", avatarId: "lamb-god-shiny", title: "Lamb of God" },
  { id: "shiny-eagle-wings", name: "Eagle's Wings", hint: "Reach a 90-day prayer streak", avatarId: "eagle-wings-shiny", title: "Eagle's Wings" },
  { id: "shiny-raven-elijah", name: "Raven's Provision", hint: "Complete a 90-day fast", avatarId: "raven-provision-shiny", title: "Raven's Provision" },
  { id: "shiny-paul-dove", name: "Paul: Inspired", hint: "Reach a 100-day prayer streak", title: "Paul Inspired" },
  { id: "shiny-daniel-dove", name: "Daniel: Protected", hint: "Complete a 100-day fast", title: "Daniel Protected" },
  { id: "shiny-joseph-dove", name: "Joseph: Dreamer", hint: "Reach a 120-day prayer streak", title: "Joseph Dreamer" },
  { id: "shiny-fish-loaves", name: "Loaves & Fishes", hint: "Complete a 120-day fast", title: "Loaves & Fishes" },
  { id: "shiny-donkey-triumph", name: "Triumphal Donkey", hint: "Reach a 150-day prayer streak", title: "Triumphal Donkey" },
  { id: "shiny-sheep-shepherd", name: "The Lost Sheep", hint: "Complete a 150-day fast", title: "Lost Sheep" },
] as const;
export type AchievementId = (typeof SHINY_ACHIEVEMENTS)[number]["id"];

const STYLE_ORDER: AvatarStyle[] = ["1920s", "1950s", "1970s", "1980s", "90s", "Y2K"];
export { STYLE_ORDER };

export function avatarDefinitionById(id?: string) { return AVATAR_DEFINITIONS.find((avatar) => avatar.id === id); }

export function getAvatarDefinitionForPerson(id: string, gender?: AvatarGender, avatarAsset?: string) {
  const selected = avatarDefinitionById(avatarAsset);
  // Keep the original initials circle until the user explicitly chooses a
  // bundled avatar. The arguments remain in this API for caller compatibility.
  void id;
  void gender;
  return selected;
}

export function getAvatarAssetForPerson(id: string, gender?: AvatarGender, avatarAsset?: string) {
  return getAvatarDefinitionForPerson(id, gender, avatarAsset)?.id;
}
