export type BookAuraStyle = "rays" | "rings" | "stained-glass" | "embers" | "stars" | "dust" | "radiant" | "prismatic";
export type BookAvatarAuraConfig = { id: string; book: string; label: string; glowColor: string; secondaryColor: string; accentColors: string[]; style: BookAuraStyle; ringCount: number };

export const BOOK_AVATAR_AURAS: Record<string, BookAvatarAuraConfig> = {
  "book-genesis": { id: "book-genesis", book: "Genesis", label: "Genesis", glowColor: "#C2410C", secondaryColor: "#4F46E5", accentColors: ["#B91C1C"], style: "rays", ringCount: 1 },
  "book-exodus": { id: "book-exodus", book: "Exodus", label: "Exodus", glowColor: "#B45309", secondaryColor: "#7C3AED", accentColors: ["#A16207"], style: "rings", ringCount: 3 },
  "book-leviticus": { id: "book-leviticus", book: "Leviticus", label: "Leviticus", glowColor: "#15803D", secondaryColor: "#9333EA", accentColors: ["#047857"], style: "stained-glass", ringCount: 1 },
  "book-numbers": { id: "book-numbers", book: "Numbers", label: "Numbers", glowColor: "#0F766E", secondaryColor: "#BE185D", accentColors: ["#0369A1"], style: "embers", ringCount: 1 },
  "book-deuteronomy": { id: "book-deuteronomy", book: "Deuteronomy", label: "Deuteronomy", glowColor: "#2563EB", secondaryColor: "#B91C1C", accentColors: ["#1D4ED8"], style: "stars", ringCount: 1 },
  "book-joshua": { id: "book-joshua", book: "Joshua", label: "Joshua", glowColor: "#4F46E5", secondaryColor: "#A16207", accentColors: ["#4338CA"], style: "dust", ringCount: 1 },
  "book-judges": { id: "book-judges", book: "Judges", label: "Judges", glowColor: "#7C3AED", secondaryColor: "#047857", accentColors: ["#6D28D9"], style: "radiant", ringCount: 1 },
  "book-ruth": { id: "book-ruth", book: "Ruth", label: "Ruth", glowColor: "#9333EA", secondaryColor: "#0369A1", accentColors: ["#86198F"], style: "prismatic", ringCount: 1 },
  "book-1samuel": { id: "book-1samuel", book: "1 Samuel", label: "1 Samuel", glowColor: "#BE185D", secondaryColor: "#1D4ED8", accentColors: ["#9D174D"], style: "rays", ringCount: 1 },
  "book-2samuel": { id: "book-2samuel", book: "2 Samuel", label: "2 Samuel", glowColor: "#B91C1C", secondaryColor: "#4338CA", accentColors: ["#C2410C"], style: "rings", ringCount: 3 },
  "book-1kings": { id: "book-1kings", book: "1 Kings", label: "1 Kings", glowColor: "#A16207", secondaryColor: "#6D28D9", accentColors: ["#B45309"], style: "stained-glass", ringCount: 1 },
  "book-2kings": { id: "book-2kings", book: "2 Kings", label: "2 Kings", glowColor: "#047857", secondaryColor: "#86198F", accentColors: ["#15803D"], style: "embers", ringCount: 1 },
  "book-1chronicles": { id: "book-1chronicles", book: "1 Chronicles", label: "1 Chronicles", glowColor: "#0369A1", secondaryColor: "#9D174D", accentColors: ["#0F766E"], style: "stars", ringCount: 1 },
  "book-2chronicles": { id: "book-2chronicles", book: "2 Chronicles", label: "2 Chronicles", glowColor: "#1D4ED8", secondaryColor: "#C2410C", accentColors: ["#2563EB"], style: "dust", ringCount: 1 },
  "book-ezra": { id: "book-ezra", book: "Ezra", label: "Ezra", glowColor: "#4338CA", secondaryColor: "#B45309", accentColors: ["#4F46E5"], style: "radiant", ringCount: 1 },
  "book-nehemiah": { id: "book-nehemiah", book: "Nehemiah", label: "Nehemiah", glowColor: "#6D28D9", secondaryColor: "#15803D", accentColors: ["#7C3AED"], style: "prismatic", ringCount: 1 },
  "book-esther": { id: "book-esther", book: "Esther", label: "Esther", glowColor: "#86198F", secondaryColor: "#0F766E", accentColors: ["#9333EA"], style: "rays", ringCount: 1 },
  "book-job": { id: "book-job", book: "Job", label: "Job", glowColor: "#9D174D", secondaryColor: "#2563EB", accentColors: ["#BE185D"], style: "rings", ringCount: 3 },
  "book-psalms": { id: "book-psalms", book: "Psalms", label: "Psalms", glowColor: "#C2410C", secondaryColor: "#4F46E5", accentColors: ["#B91C1C"], style: "stained-glass", ringCount: 1 },
  "book-proverbs": { id: "book-proverbs", book: "Proverbs", label: "Proverbs", glowColor: "#B45309", secondaryColor: "#7C3AED", accentColors: ["#A16207"], style: "embers", ringCount: 1 },
  "book-ecclesiastes": { id: "book-ecclesiastes", book: "Ecclesiastes", label: "Ecclesiastes", glowColor: "#15803D", secondaryColor: "#9333EA", accentColors: ["#047857"], style: "stars", ringCount: 1 },
  "book-songofsolomon": { id: "book-songofsolomon", book: "Song of Solomon", label: "Song of Solomon", glowColor: "#0F766E", secondaryColor: "#BE185D", accentColors: ["#0369A1"], style: "dust", ringCount: 1 },
  "book-isaiah": { id: "book-isaiah", book: "Isaiah", label: "Isaiah", glowColor: "#2563EB", secondaryColor: "#B91C1C", accentColors: ["#1D4ED8"], style: "radiant", ringCount: 1 },
  "book-jeremiah": { id: "book-jeremiah", book: "Jeremiah", label: "Jeremiah", glowColor: "#4F46E5", secondaryColor: "#A16207", accentColors: ["#4338CA"], style: "prismatic", ringCount: 1 },
  "book-lamentations": { id: "book-lamentations", book: "Lamentations", label: "Lamentations", glowColor: "#7C3AED", secondaryColor: "#047857", accentColors: ["#6D28D9"], style: "rays", ringCount: 1 },
  "book-ezekiel": { id: "book-ezekiel", book: "Ezekiel", label: "Ezekiel", glowColor: "#9333EA", secondaryColor: "#0369A1", accentColors: ["#86198F"], style: "rings", ringCount: 3 },
  "book-daniel": { id: "book-daniel", book: "Daniel", label: "Daniel", glowColor: "#BE185D", secondaryColor: "#1D4ED8", accentColors: ["#9D174D"], style: "stained-glass", ringCount: 1 },
  "book-hosea": { id: "book-hosea", book: "Hosea", label: "Hosea", glowColor: "#B91C1C", secondaryColor: "#4338CA", accentColors: ["#C2410C"], style: "embers", ringCount: 1 },
  "book-joel": { id: "book-joel", book: "Joel", label: "Joel", glowColor: "#A16207", secondaryColor: "#6D28D9", accentColors: ["#B45309"], style: "stars", ringCount: 1 },
  "book-amos": { id: "book-amos", book: "Amos", label: "Amos", glowColor: "#047857", secondaryColor: "#86198F", accentColors: ["#15803D"], style: "dust", ringCount: 1 },
  "book-obadiah": { id: "book-obadiah", book: "Obadiah", label: "Obadiah", glowColor: "#0369A1", secondaryColor: "#9D174D", accentColors: ["#0F766E"], style: "radiant", ringCount: 1 },
  "book-jonah": { id: "book-jonah", book: "Jonah", label: "Jonah", glowColor: "#1D4ED8", secondaryColor: "#C2410C", accentColors: ["#2563EB"], style: "prismatic", ringCount: 1 },
  "book-micah": { id: "book-micah", book: "Micah", label: "Micah", glowColor: "#4338CA", secondaryColor: "#B45309", accentColors: ["#4F46E5"], style: "rays", ringCount: 1 },
  "book-nahum": { id: "book-nahum", book: "Nahum", label: "Nahum", glowColor: "#6D28D9", secondaryColor: "#15803D", accentColors: ["#7C3AED"], style: "rings", ringCount: 3 },
  "book-habakkuk": { id: "book-habakkuk", book: "Habakkuk", label: "Habakkuk", glowColor: "#86198F", secondaryColor: "#0F766E", accentColors: ["#9333EA"], style: "stained-glass", ringCount: 1 },
  "book-zephaniah": { id: "book-zephaniah", book: "Zephaniah", label: "Zephaniah", glowColor: "#9D174D", secondaryColor: "#2563EB", accentColors: ["#BE185D"], style: "embers", ringCount: 1 },
  "book-haggai": { id: "book-haggai", book: "Haggai", label: "Haggai", glowColor: "#C2410C", secondaryColor: "#4F46E5", accentColors: ["#B91C1C"], style: "stars", ringCount: 1 },
  "book-zechariah": { id: "book-zechariah", book: "Zechariah", label: "Zechariah", glowColor: "#B45309", secondaryColor: "#7C3AED", accentColors: ["#A16207"], style: "dust", ringCount: 1 },
  "book-malachi": { id: "book-malachi", book: "Malachi", label: "Malachi", glowColor: "#15803D", secondaryColor: "#9333EA", accentColors: ["#047857"], style: "radiant", ringCount: 1 },
  "book-matthew": { id: "book-matthew", book: "Matthew", label: "Matthew", glowColor: "#0F766E", secondaryColor: "#BE185D", accentColors: ["#0369A1"], style: "prismatic", ringCount: 1 },
  "book-mark": { id: "book-mark", book: "Mark", label: "Mark", glowColor: "#2563EB", secondaryColor: "#B91C1C", accentColors: ["#1D4ED8"], style: "rays", ringCount: 1 },
  "book-luke": { id: "book-luke", book: "Luke", label: "Luke", glowColor: "#4F46E5", secondaryColor: "#A16207", accentColors: ["#4338CA"], style: "rings", ringCount: 3 },
  "book-john": { id: "book-john", book: "John", label: "John", glowColor: "#7C3AED", secondaryColor: "#047857", accentColors: ["#6D28D9"], style: "stained-glass", ringCount: 1 },
  "book-acts": { id: "book-acts", book: "Acts", label: "Acts", glowColor: "#9333EA", secondaryColor: "#0369A1", accentColors: ["#86198F"], style: "embers", ringCount: 1 },
  "book-romans": { id: "book-romans", book: "Romans", label: "Romans", glowColor: "#BE185D", secondaryColor: "#1D4ED8", accentColors: ["#9D174D"], style: "stars", ringCount: 1 },
  "book-1corinthians": { id: "book-1corinthians", book: "1 Corinthians", label: "1 Corinthians", glowColor: "#B91C1C", secondaryColor: "#4338CA", accentColors: ["#C2410C"], style: "dust", ringCount: 1 },
  "book-2corinthians": { id: "book-2corinthians", book: "2 Corinthians", label: "2 Corinthians", glowColor: "#A16207", secondaryColor: "#6D28D9", accentColors: ["#B45309"], style: "radiant", ringCount: 1 },
  "book-galatians": { id: "book-galatians", book: "Galatians", label: "Galatians", glowColor: "#047857", secondaryColor: "#86198F", accentColors: ["#15803D"], style: "prismatic", ringCount: 1 },
  "book-ephesians": { id: "book-ephesians", book: "Ephesians", label: "Ephesians", glowColor: "#0369A1", secondaryColor: "#9D174D", accentColors: ["#0F766E"], style: "rays", ringCount: 1 },
  "book-philippians": { id: "book-philippians", book: "Philippians", label: "Philippians", glowColor: "#1D4ED8", secondaryColor: "#C2410C", accentColors: ["#2563EB"], style: "rings", ringCount: 3 },
  "book-colossians": { id: "book-colossians", book: "Colossians", label: "Colossians", glowColor: "#4338CA", secondaryColor: "#B45309", accentColors: ["#4F46E5"], style: "stained-glass", ringCount: 1 },
  "book-1thessalonians": { id: "book-1thessalonians", book: "1 Thessalonians", label: "1 Thessalonians", glowColor: "#6D28D9", secondaryColor: "#15803D", accentColors: ["#7C3AED"], style: "embers", ringCount: 1 },
  "book-2thessalonians": { id: "book-2thessalonians", book: "2 Thessalonians", label: "2 Thessalonians", glowColor: "#86198F", secondaryColor: "#0F766E", accentColors: ["#9333EA"], style: "stars", ringCount: 1 },
  "book-1timothy": { id: "book-1timothy", book: "1 Timothy", label: "1 Timothy", glowColor: "#9D174D", secondaryColor: "#2563EB", accentColors: ["#BE185D"], style: "dust", ringCount: 1 },
  "book-2timothy": { id: "book-2timothy", book: "2 Timothy", label: "2 Timothy", glowColor: "#C2410C", secondaryColor: "#4F46E5", accentColors: ["#B91C1C"], style: "radiant", ringCount: 1 },
  "book-titus": { id: "book-titus", book: "Titus", label: "Titus", glowColor: "#B45309", secondaryColor: "#7C3AED", accentColors: ["#A16207"], style: "prismatic", ringCount: 1 },
  "book-philemon": { id: "book-philemon", book: "Philemon", label: "Philemon", glowColor: "#15803D", secondaryColor: "#9333EA", accentColors: ["#047857"], style: "rays", ringCount: 1 },
  "book-hebrews": { id: "book-hebrews", book: "Hebrews", label: "Hebrews", glowColor: "#0F766E", secondaryColor: "#BE185D", accentColors: ["#0369A1"], style: "rings", ringCount: 3 },
  "book-james": { id: "book-james", book: "James", label: "James", glowColor: "#2563EB", secondaryColor: "#B91C1C", accentColors: ["#1D4ED8"], style: "stained-glass", ringCount: 1 },
  "book-1peter": { id: "book-1peter", book: "1 Peter", label: "1 Peter", glowColor: "#4F46E5", secondaryColor: "#A16207", accentColors: ["#4338CA"], style: "embers", ringCount: 1 },
  "book-2peter": { id: "book-2peter", book: "2 Peter", label: "2 Peter", glowColor: "#7C3AED", secondaryColor: "#047857", accentColors: ["#6D28D9"], style: "stars", ringCount: 1 },
  "book-1john": { id: "book-1john", book: "1 John", label: "1 John", glowColor: "#9333EA", secondaryColor: "#0369A1", accentColors: ["#86198F"], style: "dust", ringCount: 1 },
  "book-2john": { id: "book-2john", book: "2 John", label: "2 John", glowColor: "#BE185D", secondaryColor: "#1D4ED8", accentColors: ["#9D174D"], style: "radiant", ringCount: 1 },
  "book-3john": { id: "book-3john", book: "3 John", label: "3 John", glowColor: "#B91C1C", secondaryColor: "#4338CA", accentColors: ["#C2410C"], style: "prismatic", ringCount: 1 },
  "book-jude": { id: "book-jude", book: "Jude", label: "Jude", glowColor: "#A16207", secondaryColor: "#6D28D9", accentColors: ["#B45309"], style: "rays", ringCount: 1 },
  "book-revelation": { id: "book-revelation", book: "Revelation", label: "Revelation", glowColor: "#047857", secondaryColor: "#86198F", accentColors: ["#15803D"], style: "rings", ringCount: 3 },
};

export function getCompletedBookAvatarIds(bookStatuses: Record<string, string | undefined>) {
  return Object.values(BOOK_AVATAR_AURAS).filter((entry) => bookStatuses[entry.book] === "complete").map((entry) => entry.id);
}
