from pathlib import Path

path = Path('/home/ubuntu/recreated-prayer-app/app/(tabs)/index.tsx')
text = path.read_text()

replacements = [
    (
        'import AsyncStorage from "@react-native-async-storage/async-storage";\nimport MaterialIcons from "@expo/vector-icons/MaterialIcons";\nimport { useEffect, useMemo, useState } from "react";\nimport { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";',
        'import AsyncStorage from "@react-native-async-storage/async-storage";\nimport MaterialIcons from "@expo/vector-icons/MaterialIcons";\nimport * as ImagePicker from "expo-image-picker";\nimport { useRouter } from "expo-router";\nimport { useEffect, useMemo, useState } from "react";\nimport { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";'
    ),
    (
        '  calculatePrayerStreak,\n  getInitialState,\n  getPrayTodayList,\n  getTodayISOString,',
        '  calculatePrayerStreak,\n  formatDaysSinceLastPrayer,\n  getDaysSinceLastPrayed,\n  getInitialState,\n  getLastReachedAccentColor,\n  getPrayTodayList,\n  getTodayISOString,\n  getUrgentPrayerItems,'
    ),
    (
        '} from "@/lib/prayercircle-data";\n',
        '} from "@/lib/prayercircle-data";\nimport { PEOPLE_STORAGE_KEY } from "@/lib/prayercircle-storage";\n'
    ),
    ('const ADD_SCREEN_BG = "#EEF8FF";\nconst PEOPLE_STORAGE_KEY = "prayercircle.people.v1";', 'const ADD_SCREEN_BG = "#EEF8FF";'),
    ('export default function HomeScreen() {\n  const today = getTodayISOString();', 'export default function HomeScreen() {\n  const router = useRouter();\n  const today = getTodayISOString();'),
    ('  const [newPersonBirthday, setNewPersonBirthday] = useState("");\n  const [newPersonNote, setNewPersonNote] = useState("");', '  const [newPersonBirthday, setNewPersonBirthday] = useState("");\n  const [newPersonNote, setNewPersonNote] = useState("");\n  const [newPersonPhotoUri, setNewPersonPhotoUri] = useState<string | undefined>(undefined);'),
    ('    setNewPersonBirthday("");\n    setNewPersonNote("");\n  };', '    setNewPersonBirthday("");\n    setNewPersonNote("");\n    setNewPersonPhotoUri(undefined);\n  };'),
    ('  const handleAddPerson = () => {', '  const handlePickNewPersonPhoto = async () => {\n    const result = await ImagePicker.launchImageLibraryAsync({\n      mediaTypes: ImagePicker.MediaTypeOptions.Images,\n      allowsEditing: true,\n      aspect: [1, 1],\n      quality: 0.85,\n    });\n\n    if (!result.canceled && result.assets[0]?.uri) {\n      setNewPersonPhotoUri(result.assets[0].uri);\n    }\n  };\n\n  const handleAddPerson = () => {'),
    ('      birthday: newPersonBirthday,\n      prayerNote: newPersonNote,\n      reminderDaysOfWeek: [todayDayOfWeek],\n      reminderTag: newPersonNote.split(" ").slice(0, 2).join(" "),', '      birthday: newPersonBirthday,\n      prayerNote: newPersonNote,\n      reminderDaysOfWeek: [],\n      reminderTag: newPersonNote.split(" ").slice(0, 2).join(" "),\n      photoUri: newPersonPhotoUri,'),
    ('        <Text style={[styles.avatarText, { fontSize: textSize, color: person.avatarColor === "#2B151C" ? "#FFFFFF" : DEEP_TEXT }]}>\n          {label}\n        </Text>', '        {person.photoUri ? (\n          <Image source={{ uri: person.photoUri }} style={{ width: size, height: size, borderRadius: size / 2 }} />\n        ) : (\n          <Text style={[styles.avatarText, { fontSize: textSize, color: person.avatarColor === "#2B151C" ? "#FFFFFF" : DEEP_TEXT }]}>\n            {label}\n          </Text>\n        )}'),
    ('  const renderStoryPerson = (person: Person) => (\n    <View key={`story-${person.id}`} style={styles.storyItem}>\n      {person.reminderTag ? (\n        <View style={styles.storyTag}>\n          <Text numberOfLines={1} style={styles.storyTagText}>{person.reminderTag}</Text>\n        </View>\n      ) : null}\n      <View style={styles.storyRing}>{renderAvatar(person, 54, true)}</View>\n      <View style={styles.storyPlus}>\n        <MaterialIcons name={iconName("add")} size={26} color="#FFFFFF" />\n      </View>\n    </View>\n  );', '  const renderStoryPerson = (person: Person) => {\n    const urgentItems = getUrgentPrayerItems(person);\n    return (\n      <Pressable key={`story-${person.id}`} onPress={() => router.push({ pathname: "/person", params: { personId: person.id } })} style={({ pressed }) => [styles.storyItem, pressed && styles.pressed]}>\n        {urgentItems.length > 0 ? (\n          <View style={styles.storyTag}>\n            <Text numberOfLines={1} style={styles.storyTagText}>⚡ {urgentItems[0].title}</Text>\n          </View>\n        ) : null}\n        <View style={styles.storyRing}>{renderAvatar(person, 54, true)}</View>\n        <View style={styles.storyPlus}>\n          <MaterialIcons name={iconName("chevron-right")} size={23} color="#FFFFFF" />\n        </View>\n      </Pressable>\n    );\n  };'),
    ('  const renderPersonCard = (person: Person) => (\n    <View key={person.id} style={styles.personCard}>\n      {renderAvatar(person, 52)}\n      <View style={styles.personInfo}>\n        <Text numberOfLines={1} style={styles.personName}>{person.name}</Text>\n        <Text numberOfLines={1} style={styles.personMeta}>\n          {person.relationship} • Prayed today{getBirthdayText(person)}\n        </Text>\n      </View>\n      <View style={styles.cardActions}>\n        <Pressable style={({ pressed }) => [styles.minusPill, pressed && styles.pressed]}>\n          <MaterialIcons name={iconName("remove")} size={22} color="#8B8199" />\n        </Pressable>\n        <Pressable style={({ pressed }) => [styles.editButton, pressed && styles.pressed]}>\n          <MaterialIcons name={iconName("edit")} size={24} color="#77737D" />\n        </Pressable>\n      </View>\n    </View>\n  );', '  const renderPersonCard = (person: Person) => {\n    const daysSince = getDaysSinceLastPrayed(person.lastPrayedDate);\n    const progressColor = getLastReachedAccentColor(person);\n    const progressWidth = daysSince === 999 ? "100%" : `${Math.min(100, Math.max(10, (daysSince / 21) * 100))}%`;\n    return (\n      <Pressable key={person.id} onPress={() => router.push({ pathname: "/person", params: { personId: person.id } })} style={({ pressed }) => [styles.personCard, pressed && styles.pressed]}>\n        {renderAvatar(person, 52)}\n        <View style={styles.personInfo}>\n          <Text numberOfLines={1} style={styles.personName}>{person.name}</Text>\n          <Text numberOfLines={1} style={styles.personMeta}>\n            {person.relationship} • {daysSince === 999 ? "Not reached yet" : `${formatDaysSinceLastPrayer(daysSince)} since reached`}{getBirthdayText(person)}\n          </Text>\n          <View style={styles.reachProgressTrack}>\n            <View style={[styles.reachProgressFill, { width: progressWidth, backgroundColor: progressColor }]} />\n          </View>\n        </View>\n        <MaterialIcons name={iconName("chevron-right")} size={30} color="#8B8199" />\n      </Pressable>\n    );\n  };'),
    ('            <Text style={styles.emptyInlineText}>Add a person to build today’s prayer row.</Text>', '            <Text style={styles.emptyInlineText}>Set reminders on a person to build today’s prayer row.</Text>'),
    ('          <View style={styles.photoArea}>\n            <View style={styles.photoCircle}>\n              <MaterialIcons name={iconName("photo-camera")} size={44} color={PURPLE} />\n              <View style={styles.photoBadge}>\n                <MaterialIcons name={iconName("photo-camera")} size={22} color="#FFFFFF" />\n              </View>\n            </View>\n            <Text style={styles.photoPrompt}>Tap to add a photo</Text>\n          </View>', '          <Pressable onPress={handlePickNewPersonPhoto} style={({ pressed }) => [styles.photoArea, pressed && styles.pressed]}>\n            <View style={styles.photoCircle}>\n              {newPersonPhotoUri ? (\n                <Image source={{ uri: newPersonPhotoUri }} style={styles.photoPreview} />\n              ) : (\n                <MaterialIcons name={iconName("photo-camera")} size={34} color={PURPLE} />\n              )}\n              <View style={styles.photoBadge}>\n                <MaterialIcons name={iconName("add")} size={21} color="#FFFFFF" />\n              </View>\n            </View>\n            <Text style={styles.photoPrompt}>{newPersonPhotoUri ? "Change photo" : "Tap to add a photo"}</Text>\n          </Pressable>'),
    ('    bottom: 88,', '    bottom: 122,'),
    ('  cardActions: {\n    width: 74,\n    minHeight: 62,\n    alignItems: "center",\n    justifyContent: "space-between",\n  },\n  minusPill: {\n    width: 72,\n    height: 30,\n    borderRadius: 15,\n    backgroundColor: "#E9E1F0",\n    alignItems: "center",\n    justifyContent: "center",\n  },\n  editButton: {\n    width: 32,\n    height: 32,\n    borderRadius: 16,\n    alignItems: "center",\n    justifyContent: "center",\n    alignSelf: "center",\n  },', '  reachProgressTrack: {\n    marginTop: 8,\n    width: "100%",\n    height: 6,\n    borderRadius: 3,\n    backgroundColor: "#EFEAF4",\n    overflow: "hidden",\n  },\n  reachProgressFill: {\n    height: 6,\n    borderRadius: 3,\n  },'),
    ('  addTopBar: {\n    height: 99,\n    paddingHorizontal: 37,', '  addTopBar: {\n    height: 76,\n    paddingHorizontal: 24,'),
    ('    fontSize: 27,\n    fontWeight: "800",\n    lineHeight: 34,', '    fontSize: 22,\n    fontWeight: "800",\n    lineHeight: 28,'),
    ('  saveButton: {\n    minWidth: 110,\n    height: 60,\n    paddingHorizontal: 21,\n    borderRadius: 31,', '  saveButton: {\n    minWidth: 82,\n    height: 44,\n    paddingHorizontal: 18,\n    borderRadius: 22,'),
    ('    fontSize: 25,\n    fontWeight: "800",\n    lineHeight: 31,', '    fontSize: 17,\n    fontWeight: "800",\n    lineHeight: 22,'),
    ('  addContent: {\n    paddingHorizontal: 37,\n    paddingTop: 39,\n    paddingBottom: 80,', '  addContent: {\n    paddingHorizontal: 24,\n    paddingTop: 22,\n    paddingBottom: 54,'),
    ('  photoArea: {\n    alignItems: "center",\n    marginBottom: 40,\n  },\n  photoCircle: {\n    width: 160,\n    height: 160,\n    borderRadius: 80,\n    borderWidth: 4,', '  photoArea: {\n    alignItems: "center",\n    marginBottom: 22,\n  },\n  photoCircle: {\n    width: 104,\n    height: 104,\n    borderRadius: 52,\n    borderWidth: 3,'),
    ('  photoBadge: {\n    position: "absolute",\n    right: -2,\n    bottom: 26,\n    width: 43,\n    height: 43,\n    borderRadius: 22,', '  photoBadge: {\n    position: "absolute",\n    right: -2,\n    bottom: 11,\n    width: 35,\n    height: 35,\n    borderRadius: 18,'),
    ('  photoPrompt: {\n    marginTop: 20,\n    color: "#687582",\n    fontSize: 24,\n    fontWeight: "500",\n    lineHeight: 30,\n  },', '  photoPreview: {\n    width: 98,\n    height: 98,\n    borderRadius: 49,\n  },\n  photoPrompt: {\n    marginTop: 10,\n    color: "#687582",\n    fontSize: 15,\n    fontWeight: "700",\n    lineHeight: 20,\n  },'),
    ('  fieldLabel: {\n    marginBottom: 14,\n    color: "#56646F",\n    fontSize: 19,', '  fieldLabel: {\n    marginBottom: 8,\n    color: "#56646F",\n    fontSize: 13,'),
    ('  textInput: {\n    minHeight: 77,\n    marginBottom: 37,\n    paddingHorizontal: 22,', '  textInput: {\n    minHeight: 50,\n    marginBottom: 20,\n    paddingHorizontal: 15,'),
    ('    fontSize: 27,\n    fontWeight: "500",\n    lineHeight: 34,', '    fontSize: 16,\n    fontWeight: "600",\n    lineHeight: 21,'),
    ('  relationshipPills: {\n    flexDirection: "row",\n    flexWrap: "wrap",\n    gap: 13,\n    marginBottom: 38,', '  relationshipPills: {\n    flexDirection: "row",\n    flexWrap: "wrap",\n    gap: 8,\n    marginBottom: 20,'),
    ('  relationshipPill: {\n    minHeight: 62,\n    paddingHorizontal: 23,\n    borderRadius: 31,', '  relationshipPill: {\n    minHeight: 42,\n    paddingHorizontal: 15,\n    borderRadius: 21,'),
    ('    fontSize: 25,\n    fontWeight: "800",\n    lineHeight: 30,', '    fontSize: 15,\n    fontWeight: "800",\n    lineHeight: 20,'),
    ('  fieldHint: {\n    marginTop: -24,\n    marginBottom: 39,\n    color: "#6B7782",\n    fontSize: 18,\n    fontWeight: "500",\n    lineHeight: 24,', '  fieldHint: {\n    marginTop: -12,\n    marginBottom: 20,\n    color: "#6B7782",\n    fontSize: 12,\n    fontWeight: "600",\n    lineHeight: 17,'),
    ('  notesInput: {\n    minHeight: 154,\n    paddingTop: 22,\n    lineHeight: 33,', '  notesInput: {\n    minHeight: 96,\n    paddingTop: 13,\n    lineHeight: 21,'),
]

for old, new in replacements:
    if old not in text:
        raise SystemExit(f'Missing expected snippet:\n{old[:300]}')
    text = text.replace(old, new, 1)

# Remove Alert import if it remains unused after validation; keep at this stage for future validation messaging.
path.write_text(text)
print('patched home screen')
